'use client';
import {ForestArt} from './forest-art';
import {useRef,useState} from 'react';
import {BookOpen,CheckCircle2,ClipboardCheck,HelpCircle,Lightbulb,MapPin,MessageCircle,PlayCircle,ShieldCheck,Users,GraduationCap,Sprout,CalendarDays} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import guideData from '@/lib/academy/role-guides.json';
const guideFor=(role:string)=>guideData.find(g=>g.role===role)||guideData.find(g=>g.role==='learner')!;
export function GuideEntry({role,nav}:any){const g=guideFor(role);return <section className="guide-entry"><span><BookOpen/></span><div><b>{role==='learner'?'Jak se s akademií učí?':g.title}</b><p>{role==='learner'?'Ukázka, vlastní pokus, rada instruktora. Provedeme tě jednotlivými kroky.':'Stručný postup, skutečná tlačítka a jasný výsledek každého kroku.'}</p></div><Button variant="outline" onClick={()=>nav('/navod')}><PlayCircle/>Otevřít návod</Button></section>}
export function AcademyGuide({user,nav}:any){const [selected,setSelected]=useState(user.role),[step,setStep]=useState(0);const title=useRef<HTMLHeadingElement>(null);const g=guideFor(selected),own=selected===user.role;const all=['admin','coordinator','ivp_quality'].includes(user.role);const visible=guideData.filter(x=>all||x.role===user.role||x.role==='learner');const changeRole=(v:string)=>{setSelected(v);setStep(0)};return <div className="academy-guide">
 <div className="guide-heading"><span className="section-icon"><BookOpen/></span><div><p className="kicker">PRŮVODCE AKADEMIÍ · {g.name.toUpperCase()}</p><h1 ref={title} tabIndex={-1}>{g.title}</h1><p>{g.purpose}</p></div></div>
 {visible.length>1&&<div className="guide-selector"><label htmlFor="guide-role">Čí postup si chceš projít?</label><Select value={selected} onValueChange={changeRole}><SelectTrigger id="guide-role"><SelectValue/></SelectTrigger><SelectContent>{visible.map(x=><SelectItem key={x.role} value={x.role}>{x.name}{x.role===user.role?' · moje role':''}</SelectItem>)}</SelectContent></Select><small>Výběr mění pouze návod. Přihlášený účet zůstává {user.roleLabel}.</small></div>}
 <div className="guide-layout"><div><div className="guide-section-heading"><ClipboardCheck/><h2>Postup krok za krokem</h2><span>{g.steps.length} kroků</span></div><ol className="guide-steps">{g.steps.map((item,i)=><li key={item.title}><details open={step===i} onToggle={e=>{if(e.currentTarget.open&&step!==i)setStep(i)}}><summary><span className="guide-step-number">{i+1}</span><span><b>{item.title}</b><small>{item.where}</small></span></summary><div className="guide-step-body"><p>{item.action}</p><div className="guide-step-result"><CheckCircle2/><p><b>Poznáš, že můžeš pokračovat</b>{item.done}</p></div>{i<g.steps.length-1&&<Button variant="outline" onClick={()=>setStep(i+1)}>Další krok návodu</Button>}</div></details></li>)}</ol>
 <div className="guide-return-actions">{own?<Button size="lg" onClick={()=>nav(g.startPath)}><PlayCircle/>{selected==='learner'?'Otevřít moje úkoly':'Přejít k mé práci'}</Button>:<Button variant="outline" onClick={()=>changeRole(user.role)}>Zpět k návodu pro mou roli</Button>}</div></div>
 <aside className="guide-aside"><ForestArt scene="guide" placement="aside"/>
 <section className="guide-handoff">
  <header className="handoff-heading"><span className="handoff-emblem"><Users aria-hidden="true"/></span><div><p>OD LEKCE K PRAXI</p><h2>Kdo na koho navazuje</h2></div></header>
  <dl className="handoff-roles">
   <div><dt><span className="handoff-role-icon"><BookOpen aria-hidden="true"/></span><strong>Studující</strong><span className="handoff-role-index" aria-hidden="true">01</span></dt><dd>Projde lekci, vyzkouší rozhodnutí a odešle vlastní vysvětlení.</dd></div>
   <div><dt><span className="handoff-role-icon"><ClipboardCheck aria-hidden="true"/></span><strong>Instruktor</strong><span className="handoff-role-index" aria-hidden="true">02</span></dt><dd>Vrátí konkrétní radu nebo potvrdí digitální přípravu. Praktický výkon pozoruje zvlášť.</dd></div>
   <div><dt><span className="handoff-role-icon"><CalendarDays aria-hidden="true"/></span><strong>Koordinace</strong><span className="handoff-role-index" aria-hidden="true">03</span></dt><dd>Naplánuje příležitost k nácviku a řeší organizaci.</dd></div>
  </dl>
 </section>
 <details className="guide-boundaries"><summary><ShieldCheck/>Co v této roli platí</summary><ul>{g.boundaries.map(x=><li key={x}>{x}</li>)}</ul></details></aside></div>
 {selected==='learner'&&<section className="guide-statuses"><h2>Co znamená stav mé lekce</h2><div>{[['Otevřít lekci','Ještě jsi neodevzdal/a výstup. Rozepsanou práci najdeš uvnitř.'],['Čeká na instruktora','Odpověď je odeslaná. Můžeš pokračovat jinou lekcí.'],['Uprav podle rady','Otevři odpověď, použij radu a znovu odešli.'],['Domluv další nácvik','Nejdřív s instruktorem domluv a proveď doporučený krok.'],['Příprava potvrzena','Instruktor přijal digitální přípravu. Práce v lese se ověřuje zvlášť.']].map(([name,text])=><article key={name}><b>{name}</b><p>{text}</p></article>)}</div></section>}
 {selected==='instructor'&&<section className="guide-feedback-example"><div className="forest-section-label"><MessageCircle/><h2>Rada, podle které jde odpověď opravit</h2></div><div><p><span>CO JE DOLOŽENÉ</span>„U vzorku B jsi správně popsal/a kořen zahnutý vzhůru.“</p><p><span>CO JEŠTĚ CHYBÍ</span>„Z odpovědi není jasné, co zkontroluješ po opravě.“</p><p><span>DALŠÍ KONKRÉTNÍ KROK</span>„Vrať se k ukázce a doplň kontrolované znaky. Potom odpověď znovu odešli.“</p></div><small>Ukázka formulace rady k modelové odpovědi; nepředepisuje výsledek hodnocení.</small><p><b>Po pozorování v praxi:</b> do dalšího kroku zapiš, kterou dovednost účastník procvičí, na jaké úloze a co příště zkontroluješ. Vrať se ke konkrétnímu nedostatku. Předchozí pozorování zůstává v historii.</p></section>}
 <section className="guide-faq"><div className="forest-section-label"><HelpCircle/><h2>Když si nejsi jistý/á</h2></div>{g.faq.map(x=><details key={x.question}><summary>{x.question}</summary><p>{x.answer}</p></details>)}</section>
 {['instructor','admin','teacher','didactic_reviewer','coordinator','ivp_quality'].includes(selected)&&<details className="guide-method"><summary><Lightbulb/>Jak je výuka postavená</summary><p>Nejdřív účastník vidí vysvětlenou ukázku. Potom vyřeší podobný případ, pojmenuje důvod a použije radu k opravě. Instruktor naváže předvedením a vedeným pokusem na skutečném pracovišti. Míra pomoci se řídí dosavadní zkušeností.</p><p>Obrázek má ukazovat důležitý znak. Krátká odpověď má doložit porozumění. Počet kliknutí, bodů ani délka textu praktickou dovednost nepotvrzují.</p><p>Metodické podklady: <a href="https://www.bibb.de/de/141447.php" target="_blank" rel="noreferrer">BIBB · didaktika profesní přípravy</a> a <a href="https://ies.ed.gov/ncee/wwc/PracticeGuide/1" target="_blank" rel="noreferrer">IES · příklady, grafické vysvětlení a procvičení</a>. Účinnost této konkrétní akademie u cílové skupiny se musí ověřit při použití.</p></details>}
 </div>}
