'use client';
import {useId,useState} from 'react';
import {Sprout,Trees,TreePine,Leaf,Shovel,Droplets,Package,Eye,ClipboardCheck,ShieldCheck,MapPin,Wrench,Target,HelpCircle,CheckCircle2,RotateCcw,BookOpen,PlayCircle,Users,ChevronDown,Lightbulb,FileText,TreeDeciduous,ZoomIn} from 'lucide-react';
import {SeedlingComparison,FenceComparison} from './forestry-visual-support';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
const icons:any={sprout:Sprout,trees:Trees,pine:TreePine,leaf:Leaf,shovel:Shovel,droplet:Droplets,package:Package,eye:Eye,clipboard:ClipboardCheck,shield:ShieldCheck,map:MapPin,wrench:Wrench,target:Target,help:HelpCircle};
export function PlantingDiagram(){const id=useId();return <figure><svg className="forest-root-diagram" viewBox="0 0 640 280" role="img" aria-labelledby={id+'-title '+id+'-desc'}><title id={id+'-title'}>Porovnání uložení kořenů</title><desc id={id+'-desc'}>Vlevo kořeny směřují přirozeně dolů a do stran v půdě. Vpravo je hlavní kořen otočený vzhůru kvůli nedostatečnému prostoru. Diagram není v měřítku.</desc><rect x="10" y="90" width="290" height="160" rx="14" fill="#e9eee5"/><rect x="340" y="90" width="290" height="160" rx="14" fill="#f1e9e2"/><path d="M15 90H295M345 90H625" stroke="#7b907d" strokeWidth="2" strokeDasharray="5 4"/><path d="M155 32V113" stroke="#377354" strokeWidth="9"/><path d="M155 113L155 214M155 145L107 189M155 159L205 207M155 179L128 220" fill="none" stroke="#87643e" strokeWidth="6" strokeLinecap="round"/><path d="M485 32V113" stroke="#377354" strokeWidth="9"/><path d="M485 113V194Q485 224 527 208Q546 196 535 162M485 145L461 164" fill="none" stroke="#a64a40" strokeWidth="6" strokeLinecap="round"/><text x="35" y="60">A · prostor pro kořeny</text><text x="356" y="60">B · kořen zahnutý vzhůru</text><text x="33" y="274">Srovnej s ukázkou instruktora</text><text x="357" y="274">Chyba, kterou musíte řešit</text></svg><figcaption>Schéma kořenového systému, bez měřítka. Hloubku a způsob výsadby určuje materiál a místní postup.</figcaption></figure>}
function SelectionDiagram(){const trees=[{id:'A',label:'Buk k podpoře',Icon:TreeDeciduous},{id:'B',label:'Určený konkurent',Icon:Trees},{id:'C',label:'Jedle k zachování',Icon:TreePine},{id:'D',label:'Nejasný případ',Icon:HelpCircle}];return <figure><div className="forest-plot-diagram">{trees.map(({id,label,Icon})=><div key={id}><Icon aria-hidden="true"/><b>{id}</b><small>{label}</small></div>)}</div><figcaption>Symboly ukazují roli v pracovní kartě. Podle tvaru této ikony druh v lese neurčujeme. Schéma neurčuje rozestupy.</figcaption></figure>}
export const botanicalPhotos=[
 {src:'./learning/spruce.jpg',title:'Smrk ztepilý',alt:'Smrková větvička s jehlicemi a pupeny',look:'Sledujte uspořádání jehlic kolem větvičky. Čtyřhranný průřez ověřte na skutečném vzorku.',credit:'Sten Porse · CC BY-SA 3.0'},
 {src:'./learning/fir.jpg',title:'Jedle bělokorá',alt:'Spodní strana jedlové větvičky s bělavými proužky jehlic',look:'Sledujte spodní stranu plochých jehlic a dva bělavé proužky.',credit:'Nefronus · CC BY-SA 4.0'},
 {src:'./learning/beech.jpg',title:'Buk lesní',alt:'Dlouhý štíhlý pupen buku',look:'Sledujte dlouhý, štíhlý a špičatý pupen. Tento znak využijete i bez listů.',credit:'© El Grafo · CC BY-SA 3.0'},
 {src:'./learning/oak.jpg',title:'Dub letní',alt:'Laločnatý list dubu letního',look:'Sledujte zaoblené laloky a krátký řapík. Jednotlivý znak vždy porovnejte s dalšími.',credit:'Dmitry Makeev · CC BY-SA 4.0'}
];
export function LearningPhoto({photo,hideName=false}:any){const [open,setOpen]=useState(false);return <figure className="botanical-photo learning-photo"><button className="photo-enlarge" onClick={()=>setOpen(true)} aria-label={'Zvětšit fotografii: '+(hideName?'pozorovaný vzorek':photo.title)}><img src={photo.src} alt={photo.alt} loading="lazy"/><span><ZoomIn size={18}/>Zvětšit</span></button><figcaption><b>{photo.look}</b><small>{photo.credit}</small></figcaption><Dialog open={open} onOpenChange={setOpen}><DialogContent className="photo-dialog"><DialogHeader><DialogTitle>{hideName?'Pozorujte znaky na vzorku':photo.title}</DialogTitle><DialogDescription>{photo.look}</DialogDescription></DialogHeader><img src={photo.src} alt={photo.alt}/><small>{photo.credit} · <a href="./learning/attribution.html" target="_blank" rel="noreferrer">Autor a licence</a></small></DialogContent></Dialog></figure>}
export function WorkOrder({rows}:any){return rows?.length?<section className="forest-work-order">
 <div className="work-order-heading"><span className="work-order-icon"><FileText/></span><div><p>ZADÁNÍ K UKÁZCE</p><h3>Pracovní karta</h3></div><span className="work-order-model">Výukový model</span></div>
 <p className="work-order-instruction">Nejdřív si přečtěte zadání. Všimni si, co máte udělat a co má zůstat.</p>
 <dl>{rows.map(([k,v]:any)=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>
 </section>:null;}
export function ForestryStudy({mission:m,showGoal=true}:any){
 const f=m.forestry;const [exampleIndex,setExampleIndex]=useState(0),[revealed,setRevealed]=useState(false);const example=f.examples[exampleIndex];
 const examplePhoto=m.id==='P01'&&m.revision===1&&exampleIndex===0?botanicalPhotos[1]:null;
 return <div className="forestry-study">
 {showGoal&&<div className="forest-goal"><Target/><div><b>Po této lekci dokážete</b><p>{f.goal}</p></div></div>}
 <p className="forest-intro">{m.lesson_text}</p>
 <div className="forest-teaching-cards">{f.cards.map((c:any,i:number)=>{const Icon=icons[c.icon]||Sprout;return <article key={c.title}><span className="forest-card-number">{i+1}</span><Icon size={34} aria-hidden="true"/><h3>{c.title}</h3>{m.id==='P01'&&m.revision===1&&botanicalPhotos[i]&&<LearningPhoto photo={botanicalPhotos[i]}/>}<p>{c.text}</p></article>})}</div>
 {m.id==='P03'&&m.revision===1&&<SeedlingComparison/>}{m.id==='P04'&&m.revision===1&&<PlantingDiagram/>}{m.id==='P06'&&m.revision===1&&<FenceComparison/>}{m.id==='R02'&&m.revision===1&&<SelectionDiagram/>}
 <WorkOrder rows={f.workOrder}/>
 <section className="forest-worked-example">
  <div className="example-heading"><span><Eye/></span><div><p>POROZUMÍM ÚČELU · UKÁZKA</p><h3>Jak přemýšlí pracovník</h3></div></div>
  <p className="example-instruction">Sledujte zdůvodnění pracovního postupu. Následující úloha ověřuje vlastní rozhodnutí.</p>
  {f.examples.length>1&&<div className="example-tabs" role="group" aria-label="Vyberte ukázku">{f.examples.map((e:any,i:number)=><Button key={e.label} variant={i===exampleIndex?'default':'outline'} aria-pressed={i===exampleIndex} onClick={()=>{setExampleIndex(i);setRevealed(false)}}>{e.label}</Button>)}</div>}
  <div className={'example-layout '+(examplePhoto?'example-with-photo':'')}>
   {examplePhoto&&<LearningPhoto key={examplePhoto.src} photo={examplePhoto} hideName/>}
   <div className="example-thinking">
    <div className="worked-observation"><span><Eye/>CO VIDÍM</span><p>{example.observation}</p></div>
    {revealed?<div className="example-explanation" role="status"><div className="worked-decision"><span><CheckCircle2/>CO UDĚLÁM</span><p>{example.decision}</p></div><div className="worked-why"><span><Lightbulb/>PROČ</span><p>{example.why}</p></div></div>:<div className="example-reveal"><p>Všiml/a sis důležitého znaku? Prohlédněte situaci, co z něj pracovník vyvodí.</p><Button variant="outline" onClick={()=>setRevealed(true)}><Lightbulb/>Ukázat rozhodnutí a důvod</Button></div>}
   </div>
  </div>
 </section>
 <details className="forest-terms"><summary><BookOpen/>Odborné pojmy pro danou činnost<ChevronDown/></summary><dl>{f.terms.map(([term,meaning]:any)=><div key={term}><dt>{term}</dt><dd>{meaning}</dd></div>)}</dl></details>
 </div>;
}
export function ForestryChecks({mission:m,training={},change,check,disabled,validation=[]}:any){const [results,setResults]=useState<any>({}),[pending,setPending]=useState('');return <div className="forest-checks"><div className="forest-section-label"><Target/><h3>Procvičte si to na konkrétních případech</h3></div><p>U každé otázky vyberte řešení a stiskněte „Ověřit a vysvětlit“. Přečtěte si důvod. Chybu můžete opravit; odpovědi se ukládají spolu s lekcí.</p>{m.forestry.checks.map((q:any,i:number)=>{const invalid=validation.find((v:any)=>v.id===q.id&&v.choice===(training[q.id]||'')&&!v.correct);const r=results[q.id];const matching=!!r&&r.choice===training[q.id];return <fieldset id={'exercise-'+q.id} tabIndex={-1} className={'forest-check '+(invalid?'is-invalid':matching&&r.correct?'is-correct':'')} key={q.id}><legend><span>{i+1}</span>{q.prompt}</legend>{invalid&&<p className="input-help" role="status">Tohle cvičení ještě potřebuje správné řešení.</p>}<RadioGroup value={training[q.id]||''} onValueChange={v=>change({...training,[q.id]:v})} disabled={disabled||!!pending} aria-label={q.prompt}>{q.options.map((o:any)=><label key={o.id} className={'forest-check-option '+(training[q.id]===o.id?'chosen':'')}><RadioGroupItem value={o.id}/>{o.text}</label>)}</RadioGroup><Button variant="outline" disabled={disabled||!training[q.id]||!!pending} onClick={async()=>{const selected=training[q.id];setPending(q.id);try{const d=await check(q.id,selected);if(d)setResults((s:any)=>({...s,[q.id]:{...d,choice:selected}}))}finally{setPending('')}}}>{matching&&r.correct?<CheckCircle2/>:<HelpCircle/>}{pending===q.id?'Ověřuji…':'Ověřit a vysvětlit'}</Button>{matching&&<div className={'forest-check-feedback '+(r.correct?'correct':'retry')} role="status">{r.correct?<CheckCircle2/>:<RotateCcw/>}<p><b>{r.correct?'Správně. ':'Zkuste znovu. '}</b>{r.feedback}</p></div>}</fieldset>})}</div>}
export function ForestryPractice({mission:m,nav}:any){const f=m.forestry;return <section className="forest-practice-brief"><div className="practice-phase-heading"><span>03</span><div><p>NAVAZUJÍCÍ NÁCVIK V LESE</p><h2>Předvedu v praxi</h2></div><Users/></div><p>{f.practice}</p><h3>Instruktor bude sledovat</h3><ul>{f.criteria.map((c:string)=><li key={c}><ClipboardCheck size={20}/>{c}</li>)}</ul><p className="forest-practice-note">Digitální příprava a výkon v lese mají samostatné hodnocení. Termín, pracoviště a podmínky nácviku domluví instruktor. U účastníků mladších 18 let se přípustný rozsah posuzuje zvlášť.</p><Button variant="outline" onClick={()=>nav('/praxe')}><Users/>Moje stanovená praxe</Button><Button variant="ghost" onClick={()=>nav('/podpora')}>Domluvit nácvik s instruktorem</Button></section>}
export function ForestrySources(_props:any){return null;}
