'use client';
import {BookOpen,CheckCircle2,FileText,MessageCircle,Paperclip,Target} from 'lucide-react';
export function InstructorSubmission({attempt:a,evidence,error,loading}:any){const m=a.snapshot;return <div className="instructor-evidence">
 <section className="evidence-assignment"><div className="forest-section-label"><BookOpen/><h3>Zadání, které účastník řešil</h3></div><p>{m.scenario}</p><p><b>{m.question}</b></p><div className="evidence-selected"><Target/><p><b>Zvolená odpověď</b><br/>{m.options.find((o:any)=>o.id===a.data.choice)?.text||'Volba není zaznamenaná.'}</p></div><details><summary>Řešení a vysvětlení pro instruktora</summary><p>{m.options.find((o:any)=>o.id===m.correct_option_id)?.text}</p><p>{m.feedback}</p></details></section>
 {m.forestry&&<details className="evidence-exercises"><summary>Procvičení · {m.forestry.checks.length} odpovědí</summary>{m.forestry.checks.map((q:any)=><div key={q.id}><p><b>{q.prompt}</b></p><p>{q.options.find((o:any)=>o.id===a.data.training?.[q.id])?.text||'Odpověď chybí.'}</p><small>{a.data.training?.[q.id]===q.correct?'Správná volba v procvičení.':'Volbu je potřeba znovu projít.'} {q.feedback}</small></div>)}</details>}
 <section><h3><FileText/>Vlastní vysvětlení · pokus {a.revision}</h3><p className="evidence-task">{m.submission_task}</p><p className="preserve evidence-answer">{a.data.answer}</p><h3>Řešení jiné situace</h3><p className="evidence-task">{m.transfer_task}</p><p className="preserve evidence-answer">{a.data.transfer}</p></section>
 <details><summary><CheckCircle2/>Kritéria této verze</summary><p className="preserve">{m.proposed_assessor_guidance}</p></details>
 <section><h3><Paperclip/>Přílohy k tomuto odevzdání</h3>{loading?<p role="status">Načítám podklady…</p>:error?<p role="alert">{error} Podklady nejsou ověřené; před hodnocením je znovu načtěte.</p>:evidence?.attachments?.length?evidence.attachments.map((f:any)=><a className="attachment-link" key={f.id} href={'/api/academy/attachment/'+f.id}>{f.name}</a>):<p className="muted">Před odevzdáním nebyla k této lekci přidána příloha. Přílohy jsou nepovinné.</p>}</section>
 {evidence?.reflection&&<section className="evidence-shared-note"><h3><MessageCircle/>Aktuálně sdílená poznámka účastníka</h3><p className="preserve">{evidence.reflection.text}</p><small>Dobrovolná poznámka může být novější než odevzdání. Není součástí hodnoceného výkonu.</small></section>}
 <p className="evidence-scope">{m.forestry&&a.content_id===m.id+'-v1'&&<>Účastník měl při psaní k dispozici pomocnou osnovu. Samostatnost posuzujte v tomto rozsahu. </>}Hodnoťte zde porozumění v digitální přípravě. Skutečné provedení práce patří do samostatného záznamu v „Pozorování v praxi“.</p>
 </div>}
