export const studyVersion='2026-10-08-v1';
export const studyBlocks=[
 {id:'Z',number:'01',title:'Rozumím lesu a zadání',subtitle:'Dřeviny, pracovní pokyn a společná řeč',scene:'M01',icon:'compass',checkpoint:'D01',output:'Převezmu zadání a vysvětlím, co udělám.'},
 {id:'O',number:'02',title:'Zakládám nový les',subtitle:'Obnova, sazenice a kvalitní výsadba',scene:'M02',icon:'sprout',checkpoint:'P04',output:'Poznám chyby výsadby a sestavím kontrolní kartu.'},
 {id:'P',number:'03',title:'Pečuji o mladé stromky',subtitle:'Buřeň, ochrana, oplocenky a půda',scene:'M03',icon:'shield',checkpoint:'P06',output:'Zkontroluji ochranu a popíšu potřebnou nápravu.'},
 {id:'R',number:'04',title:'Rozumím prořezávce',subtitle:'Koruny, výběr, směs a kontrola zásahu',scene:'M04',icon:'trees',checkpoint:'R04',output:'Porovnám výsledek s konkrétním zadáním.'},
 {id:'K',number:'05',title:'Připravuji křovinořez',subtitle:'Stroj, vybavení, prostor a péče',scene:'M07',icon:'tool',checkpoint:'K01',output:'Připravím plán kontroly stroje a pracoviště.'},
 {id:'S',number:'06',title:'Pracuji zodpovědně',subtitle:'Riziko, pomoc, kvalita a předání práce',scene:'D06',icon:'team',checkpoint:'D06',output:'Věcně předám výsledek, odchylku a další krok.'}
] as const;
export const practiceCards=[
 {id:'zadani',title:'Převezmu pracovní zadání',block:'Z',competencies:['C01','C13'],mission:'D01',scope:'Modelové předání a orientace před prací',criteria:['Ukáže místo a hranice úkolu.','Vlastními slovy zopakuje cíl a požadovanou kvalitu.','Pojmenuje nejasnost a domluví její vyřešení.']},
 {id:'sazenice',title:'Připravím sadební materiál',block:'O',competencies:['C02'],mission:'P03',scope:'Vedený nácvik s určeným sadebním materiálem',criteria:['Rozliší typ materiálu a jeho označení.','Předvede ochranu kořenů podle podmínek pracoviště.','Oddělí a ohlásí zjevně nevhodný materiál.']},
 {id:'vysadba',title:'Provedu a zkontroluji výsadbu',block:'O',competencies:['C02','C11'],mission:'P04',scope:'Výsadba podle předepsaného způsobu a ukázky instruktora',criteria:['Vysvětlí konkrétní zadání výsadby.','Provede úkon pod vedením a nepoškodí kořeny.','Porovná provedení se vzorem a opraví dovolenou chybu.']},
 {id:'ochrana',title:'Zkontroluji ochranu stromků',block:'P',competencies:['C03','C06'],mission:'P06',scope:'Mechanická ochrana a kontrola oplocení',criteria:['Rozpozná cílové stromky a místo poškození.','Zhodnotí funkčnost zadané ochrany.','Zvolí opravu v dovoleném rozsahu a zachová okolní porost.']},
 {id:'prorezavka',title:'Porovnám zásah se vzorem',block:'R',competencies:['C04','C10','C11'],mission:'R04',scope:'Pozorování a vedený nácvik ve vybraném mladém porostu',criteria:['Vysvětlí cíl zásahu a konkrétní kritéria výběru.','Zdůvodní rozhodnutí na referenční ukázce.','Průběžně kontroluje směs, ponechané stromy a škody.']},
 {id:'krov-priprava',title:'Připravím stroj a pracoviště',block:'K',competencies:['C08','C09'],mission:'K01',scope:'Kontrola konkrétního křovinořezu bez spuštění',criteria:['Najde návod konkrétního stroje a schválené osazení.','Předvede předepsanou kontrolu a vyřadí závadný prostředek.','Vysvětlí ochranné vybavení, prostor a komunikaci.']},
 {id:'krov-nacvik',title:'Předvedu vedený nácvik se strojem',block:'K',competencies:['C08','C09','C03'],mission:'K01',scope:'Pouze po skutečném ověření předpokladů, instruktáži a určení pracoviště',criteria:['Dodrží konkrétní návod a pracovní postup.','Udrží bezpečný prostor a reaguje na jeho narušení.','Chrání cílové dřeviny; bezpečně ukončí práci a předá závadu.']},
 {id:'predani',title:'Zkontroluji a předám výsledek',block:'S',competencies:['C10','C11','C12','C14'],mission:'D06',scope:'Kontrola výsledku a záznam po zadané práci',criteria:['Popíše skutečně provedený rozsah bez zkreslení.','Doloží kontrolu kvality a zaznamená odchylku.','Předá informaci určené osobě a domluví návaznost.']}
] as const;
