import legacyMissions from './presentation-missions.json';
import brushcutterCheckpoint from './study/checkpoint.json';
import {forestryMissions} from './forestry-curriculum';
const missions:any[]=[...forestryMissions,brushcutterCheckpoint,...legacyMissions];
import competencySource from './presentation-profile.json';
import moduleSource from '../../zadani/data/moduly_navrh_v0_2.json';
const questions:any[]=[];
import seed from '../../zadani/data/demo_seed.json';
export {missions,competencySource,moduleSource,questions,seed};
export const roleNames:Record<string,string>={learner:'Účastník',graduate:'Absolvent',instructor:'Instruktor',teacher:'Vyučující',content_expert:'Odborný garant',didactic_reviewer:'Didaktický garant',coordinator:'Koordinace',ivp_quality:'IVP · kvalita',lcr:'Dohled nad vzděláváním LČR',admin:'Správce'};
export const dimensions=['Porozumění smyslu','Bezpečné provedení','Kvalita','Samostatnost','Hranice kompetence'];
