/** Presentation only: source profile, versioned mission content and assessment remain authoritative. */
export const learningDesign:Record<string,{title:string;goal:string;prompt:string;takeaway:string;tryLabel:string;placeholder:string;transferLabel:string;example:{context:string;mentor:string;learner:string}}>= {
 D01:{title:'Zjistěte, kde máte pracovat',goal:'Umíte se doptat na nejasné zadání.',prompt:'„Pracujte v označené části.“ Jenže označené jsou dvě.',takeaway:'Když místo nebo rozsah není jasný, nejdřív se zeptejte.',tryLabel:'Co přesně se zeptáte?',placeholder:'Napište dvě otázky. Pak vlastními slovy zopakujte, jak zadání chápete.',transferLabel:'A když není jasné, jak má vypadat hotový výsledek?',example:{context:'Jiná situace: lektor chce přinést výukové karty. Neřekl které.',mentor:'Než vyrazím, potřebuji zjistit, které karty má na mysli.',learner:'Myslíte zelené, nebo modré karty? Kolik jich mám přinést?'}},
 D02:{title:'Evidence dokončení a ověření výsledku',goal:'Poznáte, co v záznamu chybí.',prompt:'V záznamu chybí kontrola. Kolega chce přesto označit „dokončeno“.',takeaway:'Zapište, co opravdu víte. Chybějící kontrolu si nedomýšlejte.',tryLabel:'Co chybí a co uděláte dál?',placeholder:'Chybí… Další krok bude…',transferLabel:'A když je záznam úplný, ale uvádí problém?',example:{context:'Jiná situace: v učebně chybí údaj, zda byly vrácené výukové karty spočítané.',mentor:'Prázdné políčko neznamená, že počet souhlasí.',learner:'Počet není ověřený. Předám to člověku, který má kontrolu na starosti.'}},
 D03:{title:'Předání pracovního hlášení',goal:'Druhý člověk z vašeho hlášení pozná stav a další krok.',prompt:'Část úkolu je hotová. Další část čeká na upřesnění.',takeaway:'Co je hotové? Co není jasné? Komu to předáte?',tryLabel:'Napište krátké hlášení',placeholder:'Činnost: …\nStav: …\nNejasnost: …\nPředávám: …\nDalší krok: …',transferLabel:'A když si všimnete závady nástroje?',example:{context:'Jiná situace: ve výuce chybí část podkladů pro skupinu.',mentor:'Popíšu, co vidím. Příčinu, kterou neznám, nevymýšlím.',learner:'Dvě skupiny mají podklady, třetí ne. Informaci předávám lektorovi a čekám na doplnění.'}},
 D04:{title:'Ověřte, že pokynu rozumíte',goal:'Doptáte se na neznámý výraz a zopakujete pokyn.',prompt:'„Předejte list na stanovišti JAVOR-X.“ Kde je JAVOR-X?',takeaway:'Neodhadujte význam. Doptáte se a pokyn řeknete vlastními slovy.',tryLabel:'Čemu rozumíte a na co se zeptáte?',placeholder:'Rozumím tomu, že… Potřebuji vysvětlit…',transferLabel:'A když znáte všechna slova, ale není jasné pořadí?',example:{context:'Jiná situace: „Po přestávce se sejdeme v učebně B.“ Nevíte, kde je.',mentor:'Rozumím času setkání, ale potřebuji upřesnit místo.',learner:'Po přestávce máme přijít do učebny B. Ve kterém je patře?'}},
 D05:{title:'Přerušení činnosti při neověřených podmínkách',goal:'Poznáte chvíli, kdy rozhodnutí předat odpovědné osobě.',prompt:'Podmínky se změnily. Neumíte posoudit, jestli lze bezpečně pokračovat.',takeaway:'Přerušte činnost a informujte určenou osobu. Na aplikaci nečekejte.',tryLabel:'Co sdělíte odpovědné osobě?',placeholder:'Změnilo se… Nedokážu posoudit… Informaci předávám…',transferLabel:'A když je chyba už v samotném zadání?',example:{context:'Jiná situace: dvě výukové kartičky dávají protichůdné pokyny.',mentor:'Nemám podklad pro vlastní rozhodnutí. Potřebuji upřesnění.',learner:'Pokyny si odporují. Dál nepokračuji a předávám je lektorovi k vysvětlení.'}},
 D06:{title:'Předejte práci tak, aby šlo navázat',goal:'Domluvíte další krok a předáte podstatné informace.',prompt:'Narazíte na překážku, která ovlivní i kolegu. Jeho úkol měnit nemůžete.',takeaway:'Sdělte, co se změnilo. Dohodněte konkrétní další krok.',tryLabel:'Co příště zlepšíte, s kým a kdy?',placeholder:'Příště zlepším… Pomůže mi… Zkusím to…',transferLabel:'A co řeknete člověku, který úkol přebírá?',example:{context:'Jiná situace: předáváte rozpracovaný skupinový úkol v učebně.',mentor:'Druhý člověk potřebuje vědět, kde jsem skončil/a.',learner:'První část je hotová, druhá čeká na vysvětlení od lektora. Příště si předání vyzkouším s partnerem.'}}
};
export function guideFor(m:any){return m.forestry?{title:m.title,goal:m.forestry.goal}:(m.revision??1)===1?(learningDesign[m.id]||{title:m.title,goal:m.submission_task}):{title:m.title,goal:m.submission_task};}
export function learningState(a:any){return a?.assessments?.[0]?.data?.outcome||a?.status||'new';}
export function latestAttempts(attempts:any[]){return attempts.filter(x=>!attempts.some(y=>y.mission===x.mission&&y.revision>x.revision));}
export function nextLearningAction(missions:any[],attempts:any[]){const latest=latestAttempts(attempts).filter(a=>missions.some(m=>m.id===a.mission));const returned=latest.find(x=>learningState(x)==='returned');if(returned)return {kind:'revise',mission:missions.find(m=>m.id===returned.mission),attempt:returned};const practice=latest.find(x=>learningState(x)==='practice');if(practice)return {kind:'practice',mission:missions.find(m=>m.id===practice.mission),attempt:practice};const untouched=missions.find(m=>!latest.some(a=>a.mission===m.id));if(untouched)return {kind:'start',mission:untouched};const waiting=latest.find(x=>learningState(x)==='submitted');if(waiting)return {kind:'wait',mission:missions.find(m=>m.id===waiting.mission),attempt:waiting};return {kind:'complete',mission:null};}
export function readyToSubmit(form:any){return !!form.choice&&form.answer.trim().length>=10&&form.transfer.trim().length>=5;}
export const learnerSteps=['Prohlédněte situaci','Vyberte krok','Zkuste to samostatně','Odešlete'];
