/** Presentation only: source profile, versioned mission content and assessment remain authoritative. */
export const learningDesign:Record<string,{title:string;goal:string;prompt:string;takeaway:string;tryLabel:string;placeholder:string;transferLabel:string;example:{context:string;mentor:string;learner:string}}>= {
 D01:{title:'Zjisti, kde máš pracovat',goal:'Umíš se doptat na nejasné zadání.',prompt:'„Pracujte v označené části.“ Jenže označené jsou dvě.',takeaway:'Když místo nebo rozsah není jasný, nejdřív se zeptej.',tryLabel:'Co přesně se zeptáš?',placeholder:'Napiš dvě otázky. Pak vlastními slovy zopakuj, jak zadání chápeš.',transferLabel:'A když není jasné, jak má vypadat hotový výsledek?',example:{context:'Jiná situace: lektor chce přinést výukové karty. Neřekl které.',mentor:'Než vyrazím, potřebuji zjistit, které karty má na mysli.',learner:'Myslíte zelené, nebo modré karty? Kolik jich mám přinést?'}},
 D02:{title:'Neoznačuj hotové, co není ověřené',goal:'Poznáš, co v záznamu chybí.',prompt:'V záznamu chybí kontrola. Kolega chce přesto označit „hotovo“.',takeaway:'Zapiš, co opravdu víš. Chybějící kontrolu si nedomýšlej.',tryLabel:'Co chybí a co uděláš dál?',placeholder:'Chybí… Další krok bude…',transferLabel:'A když je záznam úplný, ale uvádí problém?',example:{context:'Jiná situace: v učebně chybí údaj, zda byly vrácené výukové karty spočítané.',mentor:'Prázdné políčko neznamená, že počet souhlasí.',learner:'Počet není ověřený. Předám to člověku, který má kontrolu na starosti.'}},
 D03:{title:'Podej srozumitelné hlášení',goal:'Druhý člověk z tvého hlášení pozná stav a další krok.',prompt:'Část úkolu je hotová. Další část čeká na upřesnění.',takeaway:'Co je hotové? Co není jasné? Komu to předáš?',tryLabel:'Napiš krátké hlášení',placeholder:'Činnost: …\nStav: …\nNejasnost: …\nPředávám: …\nDalší krok: …',transferLabel:'A když si všimneš závady nástroje?',example:{context:'Jiná situace: ve výuce chybí část podkladů pro skupinu.',mentor:'Popíšu, co vidím. Příčinu, kterou neznám, nevymýšlím.',learner:'Dvě skupiny mají podklady, třetí ne. Informaci předávám lektorovi a čekám na doplnění.'}},
 D04:{title:'Ověř, že pokynu rozumíš',goal:'Doptáš se na neznámý výraz a zopakuješ pokyn.',prompt:'„Předejte list na stanovišti JAVOR-X.“ Kde je JAVOR-X?',takeaway:'Nehádej význam. Doptáš se a pokyn řekneš vlastními slovy.',tryLabel:'Čemu rozumíš a na co se zeptáš?',placeholder:'Rozumím tomu, že… Potřebuji vysvětlit…',transferLabel:'A když znáš všechna slova, ale není jasné pořadí?',example:{context:'Jiná situace: „Po přestávce se sejdeme v učebně B.“ Nevíš, kde je.',mentor:'Rozumím času setkání, ale potřebuji upřesnit místo.',learner:'Po přestávce máme přijít do učebny B. Ve kterém je patře?'}},
 D05:{title:'Zastav se, když si nejsi jistý/á',goal:'Poznáš chvíli, kdy rozhodnutí předat odpovědné osobě.',prompt:'Podmínky se změnily. Neumíš posoudit, jestli lze bezpečně pokračovat.',takeaway:'Přeruš činnost a informuj určenou osobu. Na aplikaci nečekej.',tryLabel:'Co sdělíš odpovědné osobě?',placeholder:'Změnilo se… Nedokážu posoudit… Informaci předávám…',transferLabel:'A když je chyba už v samotném zadání?',example:{context:'Jiná situace: dvě výukové kartičky dávají protichůdné pokyny.',mentor:'Nemám podklad pro vlastní rozhodnutí. Potřebuji upřesnění.',learner:'Pokyny si odporují. Dál nepokračuji a předávám je lektorovi k vysvětlení.'}},
 D06:{title:'Předej práci tak, aby šlo navázat',goal:'Domluvíš další krok a předáš podstatné informace.',prompt:'Narazíš na překážku, která ovlivní i kolegu. Jeho úkol měnit nemůžeš.',takeaway:'Řekni, co se změnilo. Domluv konkrétní další krok.',tryLabel:'Co příště zlepšíš, s kým a kdy?',placeholder:'Příště zlepším… Pomůže mi… Zkusím to…',transferLabel:'A co řekneš člověku, který úkol přebírá?',example:{context:'Jiná situace: předáváš rozpracovaný skupinový úkol v učebně.',mentor:'Druhý člověk potřebuje vědět, kde jsem skončil/a.',learner:'První část je hotová, druhá čeká na vysvětlení od lektora. Příště si předání vyzkouším s partnerem.'}}
};
export function guideFor(m:any){return m.forestry?{title:m.title,goal:m.forestry.goal}:(m.revision??1)===1?learningDesign[m.id]:{title:m.title,goal:m.submission_task};}
export function learningState(a:any){return a?.assessments?.[0]?.data?.outcome||a?.status||'new';}
export function latestAttempts(attempts:any[]){return attempts.filter(x=>!attempts.some(y=>y.mission===x.mission&&y.revision>x.revision));}
export function nextLearningAction(missions:any[],attempts:any[]){const latest=latestAttempts(attempts).filter(a=>missions.some(m=>m.id===a.mission));const returned=latest.find(x=>learningState(x)==='returned');if(returned)return {kind:'revise',mission:missions.find(m=>m.id===returned.mission),attempt:returned};const practice=latest.find(x=>learningState(x)==='practice');if(practice)return {kind:'practice',mission:missions.find(m=>m.id===practice.mission),attempt:practice};const untouched=missions.find(m=>!latest.some(a=>a.mission===m.id));if(untouched)return {kind:'start',mission:untouched};const waiting=latest.find(x=>learningState(x)==='submitted');if(waiting)return {kind:'wait',mission:missions.find(m=>m.id===waiting.mission),attempt:waiting};return {kind:'complete',mission:null};}
export function readyToSubmit(form:any){return !!form.choice&&form.answer.trim().length>=10&&form.transfer.trim().length>=5;}
export const learnerSteps=['Podívej se','Vyber krok','Zkus to sám/sama','Odešli'];
