import {subjects,studyUnits,studySources,studyBlocks,practiceCards,studyVersion,safeStudyUnit} from './study/catalog';
import {missions,competencySource,moduleSource,questions,seed,roleNames} from './catalog';
type DB={prepare:(s:string)=>any,batch:(s:any[])=>Promise<any[]>};
type Ctx={DB:DB,BUCKET:any,launcherAllowed:boolean,platform:string,operation?:string,transactionMode?:boolean};
type User={id:string,org:string,name:string,role:string,active:number};
const now=()=>new Date().toISOString();
const uid=()=>crypto.randomUUID();
const parse=(s:any,f:any={})=>{try{return typeof s==='string'?JSON.parse(s):s??f}catch{return f}};
const json=(d:any,status=200,h:any={})=>Response.json(d,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...h}});
class Fault extends Error{constructor(public status:number,message:string){super(message)}}
const fail=(s:number,m:string):never=>{throw new Fault(s,m)};
const str=(v:any,max=12000)=>typeof v==='string'?v.trim().slice(0,max):'';
const hash=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('');
const rawToken=()=>Array.from(crypto.getRandomValues(new Uint8Array(32))).map(x=>x.toString(16).padStart(2,'0')).join('');
const publicUser=(u:User)=>({id:u.id,name:u.name,role:u.role,roleLabel:roleNames[u.role],org:u.org});
const SQL=(c:Ctx,s:string,...v:any[])=>c.DB.prepare(s).bind(...v);
const one=(c:Ctx,s:string,...v:any[])=>SQL(c,s,...v).first();
const rows=async(c:Ctx,s:string,...v:any[])=>(await SQL(c,s,...v).all()).results??[];
const run=(c:Ctx,s:string,...v:any[])=>SQL(c,s,...v).run();
const log=(c:Ctx,u:User,action:string,target:string)=>run(c,'INSERT INTO audit VALUES (?,?,?,?,?,?)',uid(),u.id,u.org,action,target,now());
const learnerRoles=['learner','graduate'];
const eligible=(d:any)=>d.requirementStatus==='verified_demo'&&!!d.requirementScope&&(!d.expires||(Number.isFinite(Date.parse(d.expires))&&Date.parse(d.expires)>Date.now()));
async function pinnedMission(c:Ctx,user:string,id:string,seen?:string){const d=await one(c,'SELECT content_id FROM drafts WHERE id=?',user+':'+id);if(d&&seen&&seen!==d.content_id)fail(409,'Odpověď patří k jiné verzi zadání. Načtěte aktuální rozpracování.');if(!d&&!seen)return missionContent(c,id);const v=await one(c,"SELECT * FROM contents WHERE id=? AND mission=? AND status IN ('published_demo','superseded')",d?.content_id||seen,id);if(!v)fail(409,'Zobrazená verze není dostupná pro učení. Načtěte misi znovu.');return {...parse(v.data),contentId:v.id,revision:v.revision};}

function need(u:User,roles:string[]){if(!roles.includes(u.role))fail(403,'Pro tuto akci nemáte oprávnění.');}
async function own(c:Ctx,u:User,id:string,allowInstructor=false){const target=await one(c,'SELECT * FROM users WHERE id=? AND active=1',id);if(!target||target.org!==u.org)fail(403,'K tomuto záznamu nemáte přístup.');if(id===u.id)return target;if(allowInstructor&&u.role==='instructor'&&await one(c,'SELECT learner FROM assignments WHERE learner=? AND instructor=?',id,u.id))return target;fail(403,'K tomuto záznamu nemáte přístup.');}
function sessionToken(c:Ctx,r:Request){
 const cookie=r.headers.get('cookie')?.match(/(?:^|;\s*)academy_session=([a-f0-9]{64})(?:;|$)/)?.[1];
 const local=c.platform==='presentation-browser'?r.headers.get('x-academy-demo-session'):null;
 return local&&/^[a-f0-9]{64}$/.test(local)?local:cookie;
}
async function auth(c:Ctx,r:Request){const token=sessionToken(c,r);if(!token)fail(401,'Nejdříve otevřete svůj demonstrační účet.');const s=await one(c,'SELECT u.*,s.platform FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires>? AND u.active=1',await hash(token!),Date.now());if(!s||s.platform!==c.platform)fail(401,'Relace skončila. Otevřete svůj účet znovu.');return s as User;}
async function readBody(r:{text:()=>Promise<string>}):Promise<Record<string,any>>{const text=await r.text();if(text.length>100000)fail(413,'Požadavek je příliš velký.');let d:any;try{d=JSON.parse(text)}catch{fail(400,'Neplatný formát požadavku.');}if(!d||typeof d!=='object'||Array.isArray(d))fail(400,'Požadavek musí obsahovat pojmenované údaje.');return d;}
async function seedDemo(c:Ctx){
 const stamp=now();const stmts:any[]=[];
 for(const u of seed.learners)stmts.push(SQL(c,'INSERT OR IGNORE INTO users VALUES (?,?,?,?,1)',u.id,u.organization_id,u.display_name,u.id==='demo-a06'?'graduate':'learner'));
 const staff=[...seed.staff,{id:'demo-i02',role:'instructor',name:'DEMO Instruktor 02'},{id:'demo-l01',role:'lcr',name:'DEMO Dohled LČR'},{id:'demo-s01',role:'admin',name:'DEMO Správce'}];
 for(const u of staff)stmts.push(SQL(c,'INSERT OR IGNORE INTO users VALUES (?,?,?,?,1)',u.id,'demo-akademie',u.name,u.role));
 stmts.push(SQL(c,'INSERT OR IGNORE INTO users VALUES (?,?,?,?,1)','demo-x01','demo-isolace','DEMO Izolace','learner'));
 for(const [i,u] of seed.learners.entries())stmts.push(SQL(c,'INSERT OR IGNORE INTO assignments VALUES (?,?)',u.id,i<15?'demo-i01':'demo-i02'));
 for(const m of missions)stmts.push(SQL(c,'INSERT OR IGNORE INTO contents VALUES (?,?,?,?,?,?,?)',m.id+'-v1',m.id,1,'demo-t01','published_demo',JSON.stringify(m),stamp));
 for(const u of seed.learners.slice(0,5))stmts.push(SQL(c,'INSERT OR IGNORE INTO practice VALUES (?,?,?,1)','practice-'+u.id,u.id,JSON.stringify({title:'Předání modelového zadání ve dvojici',place:'DEMO-Sever · učebna',date:null,hours:null,season:null,scope:'Pouze bezpečný model bez nářadí a terénní práce',requirementStatus:u.id==='demo-a03'?'unknown':'verified_demo',requirementScope:u.id==='demo-a03'?null:'Porozumění pravidlům modelové aktivity',verifiedBy:u.id==='demo-a03'?null:'demo-i01',expires:null,productionEnabled:false})));
 stmts.push(SQL(c,'INSERT OR IGNORE INTO observations VALUES (?,?,?,?,?,?)','seed-critical','practice-demo-a04','demo-i01',1,JSON.stringify({dimensions:['met','practice','met','unobserved','practice'],critical:true,outcome:'practice',observation:'Syntetický příklad: účastník pokračoval v modelu přes nejasné zadání.',support:'Slovní vedení',next:'Nacvičit přerušení a předání.',reason:'Výchozí syntetický scénář',scope:'Pouze modelová situace'}),stamp));
 stmts.push(SQL(c,'INSERT OR IGNORE INTO rewards VALUES (?,?,?,?,?)','seed-a04','demo-a04',240,'Výchozí syntetické body pro ukázku kritické odchylky',stamp));
 stmts.push(SQL(c,'INSERT OR IGNORE INTO drafts VALUES (?,?,?,?,?,?,?)','demo-a02:D02','demo-a02','D02',1,'D02-v1',JSON.stringify({choice:'c',answer:'Chybí záznam skutečné kontroly.',transfer:'',reflection:''}),stamp));
 stmts.push(SQL(c,'INSERT OR IGNORE INTO settings VALUES (?,?,1)','schedule',JSON.stringify({variant:'open',durationMonths:null,grouping:'open',notes:'Délka, sezónnost a varianta 15 + 15 čekají na dohodu LČR a ČZU.'})));
 await c.DB.batch(stmts);
}
async function ensureForestry(c:Ctx){const active=missions.filter(m=>m.forestry||m.id==='K01');await c.DB.batch(active.map(m=>SQL(c,'INSERT OR IGNORE INTO contents VALUES (?,?,?,?,?,?,?)',m.id+'-v1',m.id,1,'demo-t01','published_demo',JSON.stringify(m),now())));}
async function missionContent(c:Ctx,id:string){const d=await one(c,"SELECT * FROM contents WHERE mission=? AND status='published_demo' ORDER BY revision DESC LIMIT 1",id);if(!d)fail(404,'Mise není dostupná v této verzi.');return {...parse(d.data),contentId:d.id,revision:d.revision};}
function safeMission(m:any){const {correct_option_id,feedback,proposed_assessor_guidance,...rest}=m;return {...rest,...(m.forestry?{forestry:{...m.forestry,checks:m.forestry.checks.map(({correct,feedback,...q}:any)=>q)}}:{})};}
async function attemptsFor(c:Ctx,id:string,full=false){const a=await rows(c,'SELECT * FROM attempts WHERE user_id=? ORDER BY created DESC,revision DESC',id);for(const x of a){x.data=parse(x.data);x.snapshot=full?parse(x.snapshot):safeMission(parse(x.snapshot));x.assessments=(await rows(c,'SELECT * FROM assessments WHERE attempt_id=? ORDER BY revision DESC',x.id)).map((a:any)=>({...a,data:parse(a.data)}));x.status=x.assessments[0]?.data.outcome==='accepted'?'accepted':x.assessments[0]?'returned':'submitted';}return a;}
async function entriesFor(c:Ctx,id:string){const original=(await rows(c,'SELECT * FROM portfolio_entries WHERE user_id=? ORDER BY created DESC',id)).map((x:any)=>({id:x.id,created:x.created,...parse(x.data)}));const learning=(await rows(c,'SELECT * FROM study_work WHERE user_id=? ORDER BY updated DESC',id)).map((x:any)=>({id:x.id,kind:'learning',source:'Lekce '+x.unit,occurredAt:x.updated,competencyIds:studyUnits.find((u:any)=>u.id===x.unit)?.competencies||[],evidenceIds:[],title:x.title,details:x.text,created:x.created,updated:x.updated,version:x.version,unit:x.unit,contentVersion:x.content_version,scope:'Vlastní pracovní zápis · bez hodnocení praktického výkonu'}));return [...learning,...original];}
async function portfolio(c:Ctx,u:User,id:string){await own(c,u,id);const attempts=await attemptsFor(c,id);const evidence=await rows(c,'SELECT id,mission,name,mime,size,created FROM attachments WHERE user_id=?',id);const rewards=await rows(c,'SELECT points,reason,created FROM rewards WHERE user_id=? ORDER BY created DESC',id);const records=await entriesFor(c,id);return {user:publicUser(u),attempts,records,items:[...attempts,...records],evidence,rewards,points:rewards.reduce((s:number,x:any)=>s+x.points,0),practicalCompetencies:0,awardStatus:'Čeká na schválení programu',demo:true};}
function forestryProposal(b:any,base:any){
 const f=b.forestry,d=b.decision;if(!f||!d)fail(400,'Odborná lekce vyžaduje úplnou výukovou strukturu a všechna rozhodnutí.');
 const text=(v:any)=>{if(typeof v!=='string'||!v.trim()||v.length>12000)fail(400,'Výuková položka musí mít neprázdný text do 12 000 znaků.');return v.trim();};
 const list=(v:any,min=1,max=16)=>{if(!Array.isArray(v)||v.length<min||v.length>max)fail(400,'Neplatný počet výukových položek.');return v;};
 const options=(v:any)=>{const a=list(v,2,6).map((o:any)=>({id:text(o.id),text:text(o.text)}));if(a.some((o:any)=>!(/^[a-z]$/).test(o.id))||new Set(a.map((o:any)=>o.id)).size!==a.length)fail(400,'Možnosti musí mít jedinečné jednopísmenné identifikátory.');return a;};
 const checks=list(f.checks,1,12).map((q:any)=>{const o=options(q.options);if(!o.some((x:any)=>x.id===q.correct))fail(400,'Klíč cvičení není mezi možnostmi.');const id=text(q.id);if(!/^[a-zA-Z0-9_-]{1,40}$/.test(id))fail(400,'Neplatný identifikátor cvičení.');return {id,prompt:text(q.prompt),options:o,correct:q.correct,feedback:text(q.feedback)};});if(new Set(checks.map((q:any)=>q.id)).size!==checks.length)fail(400,'Cvičení potřebují jedinečné identifikátory.');
 const o=options(d.options);if(!o.some((x:any)=>x.id===d.correct_option_id))fail(400,'Závěrečný klíč není mezi možnostmi.');
 const pairs=(a:any)=>list(a,0,12).map((p:any)=>{if(!Array.isArray(p)||p.length!==2)fail(400,'Položka karty potřebuje název a vysvětlení.');return p.map(text);});
 return {question:text(d.question),options:o,correct_option_id:d.correct_option_id,feedback:text(d.feedback),forestry:{track:base.forestry.track,goal:text(f.goal),cards:list(f.cards,1,8).map((x:any)=>({icon:text(x.icon),title:text(x.title),text:text(x.text)})),examples:list(f.examples,1,8).map((x:any)=>({label:text(x.label),observation:text(x.observation),decision:text(x.decision),why:text(x.why)})),checks,terms:pairs(f.terms),workOrder:pairs(f.workOrder||[]),practice:text(f.practice),criteria:list(f.criteria,1,12).map(text),sources:[],approval:'Studijní návrh v demonstrační recenzi. Nejde o schválení pro provoz LČR.'}};
}
function validateAssessment(b:any){if(!Array.isArray(b.dimensions)||b.dimensions.length!==5||b.dimensions.some((v:any)=>!['met','practice','unobserved','na'].includes(v)))fail(400,'Vyplňte všech pět dimenzí.');if(b.dimensions.includes('na')&&!str(b.naReason))fail(400,'Uveďte důvod „netýká se“.');if(!str(b.observation)||!str(b.next)||!str(b.support))fail(400,'Doplňte pozorování, podporu a další krok.');if(!['accepted','returned','practice'].includes(b.outcome))fail(400,'Vyberte platný výsledek.');if(b.outcome==='accepted'&&(b.critical||b.dimensions.some((x:any)=>x!=='met')))fail(409,'Kritická odchylka nebo chybějící dimenze blokuje uznání výsledku.');return {dimensions:b.dimensions,naReason:str(b.naReason),critical:b.critical===true,outcome:b.outcome,observation:str(b.observation),feedback:str(b.feedback)||str(b.observation),next:str(b.next),support:str(b.support),reason:str(b.reason),scope:'DEMO · modelová situace; nejde o ověření lesnické způsobilosti'};}
async function mutate(c:Ctx,u:User,b:any,fn:()=>Promise<any>){
 const event=str(b.eventId,100);if(!/^[a-zA-Z0-9_-]{8,100}$/.test(event))fail(400,'Chybí platný identifikátor operace.');
 const key=u.id+':'+event;const digest=await hash(JSON.stringify({operation:c.operation,body:b}));const before=await one(c,'SELECT * FROM sync WHERE id=?',key);
 if(before){if(before.hash!==digest)fail(409,'Stejná operace už obsahuje jiné údaje nebo jiný účel.');return parse(before.response);}
 const original=c.DB;const pending:any[]=[];
 const append=(statement:any,sql:string)=>{pending.push(statement);if(/^(UPDATE |INSERT INTO observations SELECT)/i.test(sql)&&/version=\?/i.test(sql)){const guard='guard:'+uid();pending.push(original.prepare("INSERT INTO sync (id,hash,response) SELECT CASE WHEN changes()=1 THEN ? ELSE NULL END,'guard','{}'").bind(guard));pending.push(original.prepare('DELETE FROM sync WHERE id=?').bind(guard));}};
 const wrap=(sql:string,values:any[]=[]):any=>{const raw=original.prepare(sql).bind(...values);return {_raw:raw,_sql:sql,bind:(...v:any[])=>wrap(sql,v),first:()=>raw.first(),all:()=>raw.all(),run:async()=>{append(raw,sql);return {meta:{changes:1}}}};};
 c.DB={prepare:(sql:string)=>wrap(sql),batch:async(ss:any[])=>{for(const q of ss)append(q._raw??q,q._sql??'');return ss.map(()=>({meta:{changes:1}}))}};
 try{const result=await fn();c.DB=original;pending.push(SQL(c,'INSERT INTO sync VALUES (?,?,?)',key,digest,JSON.stringify(result)));await original.batch(pending);return result;}
 catch(e){c.DB=original;const done=await one(c,'SELECT * FROM sync WHERE id=?',key);if(done?.hash===digest)return parse(done.response);if((e as any)?.message?.match(/constraint|UNIQUE|NOT NULL/i))fail(409,'Záznam se mezitím změnil. Načtěte aktuální verzi.');throw e;}
 finally{c.DB=original;}
}
export async function handleAcademy(r:Request,c:Ctx):Promise<Response>{c={...c,operation:new URL(r.url).pathname};let u:User|undefined;try{
 const url=new URL(r.url);const p=url.pathname.replace(/^\/api\/academy\/?/,'').split('/').filter(Boolean);const method=r.method;
 if(method!=='GET'&&method!=='HEAD'){if(c.platform!=='presentation-browser'){const origin=r.headers.get('origin');if(!origin||origin!==url.origin)fail(403,'Požadavek musí pocházet z této aplikace.');}if(Number(r.headers.get('content-length')||0)>5_500_000)fail(413,'Soubor je příliš velký.');}
 if(p[0]==='launcher'){
  if(!c.launcherAllowed)fail(403,'Demonstrační účty otevírá pouze vlastník soukromé ukázky.');await seedDemo(c);if(method==='GET')return json({accounts:(await rows(c,"SELECT * FROM users WHERE active=1 AND org='demo-akademie' ORDER BY role,id")).map(publicUser),demo:true});
  const b:any=await readBody(r);const account=await one(c,'SELECT * FROM users WHERE id=? AND active=1',str(b.account));if(!account)fail(404,'Účet nebyl nalezen.');const token=rawToken();await run(c,'INSERT INTO sessions VALUES (?,?,?,?)',await hash(token),account.id,c.platform,Date.now()+8*3600000);await log(c,account,'demo_session_opened',account.id);return json({user:publicUser(account),...(c.platform==='presentation-browser'?{demoSessionToken:token}:{})},200,{'Set-Cookie':`academy_session=${token}; Path=/; HttpOnly; SameSite=Strict; Max-Age=28800${url.protocol==='https:'?'; Secure':''}`});
 }
 if(p[0]==='shared'&&method==='GET'){
  const grant=await one(c,'SELECT s.*,u.active FROM shares s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires>? AND s.revoked=0 AND u.active=1',await hash(p[1]||''),Date.now());if(!grant)fail(404,'Sdílení skončilo nebo není platné.');const ids=parse(grant.items,[]);const all=[...await attemptsFor(c,grant.user_id),...await entriesFor(c,grant.user_id)];return json({demo:true,title:'Vybrané výsledky · DEMO',expires:grant.expires,items:all.filter((a:any)=>ids.includes(a.id)).map((a:any)=>a.kind?{id:a.id,title:a.title,status:'seen',details:a.details,created:a.created,scope:a.scope||'Vlastní záznam návštěvy ukázky · není ověření výkonu'}:({id:a.id,mission:a.mission,revision:a.revision,title:a.snapshot.title,created:a.created,status:a.status,answer:a.data.answer,transfer:a.data.transfer,feedback:a.assessments[0]?.data.feedback??null,scope:'Pouze modelová situace'}))});
 }
 u=await auth(c,r);
 if(method==='POST'&&r.headers.get('content-type')?.includes('application/json')){const b=await readBody(r.clone());if(b.expectedUserId&&b.expectedUserId!==u.id)fail(409,'Účet se změnil v jiném okně. Přihlaste se znovu; tato data nebyla uložena.');}
 if(method==='POST'&&!c.transactionMode&&['reflection','shares','mentoring','practice','requirement','content','schedule','account','portfolio-entry'].includes(p[0])){const b=await readBody(r.clone());return json(await mutate(c,u,b,async()=>{const response=await handleAcademy(r,{...c,transactionMode:true});const body:any=await response.json();if(!response.ok)fail(response.status,body.error||'Operace se nezdařila.');return body;}));}


 if(p[0]==='study'&&method==='GET'){
  let id=u.id; if(url.searchParams.has('user')){id=str(url.searchParams.get('user'),80);await own(c,u,id,true);}
  const progress=await rows(c,'SELECT * FROM study_progress WHERE user_id=? AND content_version=?',id,studyVersion);
  const works=await rows(c,'SELECT * FROM study_work WHERE user_id=? AND content_version=?',id,studyVersion);
  const allAttempts=await attemptsFor(c,id);const checkpoints=studyBlocks.map(b=>{const a=allAttempts.find((a:any)=>a.mission===b.checkpoint);return {mission:b.checkpoint,status:a?.status||'not_started',revision:a?.revision||0};});const rewards=await rows(c,'SELECT points FROM rewards WHERE user_id=?',id);
  return json({points:rewards.reduce((n:number,r:any)=>n+r.points,0),checkpoints,version:studyVersion,units:studyUnits.map(safeStudyUnit),sources:studySources,blocks:studyBlocks,practiceCards,progress:progress.map((x:any)=>({...x,answers:parse(x.answers)})),works});
 }
 if(p[0]==='study-overview'&&method==='GET'){
  need(u,['instructor','ivp_quality','coordinator','lcr']);
  const people=u.role==='instructor'?await rows(c,'SELECT u.id,u.name FROM users u JOIN assignments a ON a.learner=u.id WHERE a.instructor=? AND u.org=? AND u.active=1',u.id,u.org):await rows(c,"SELECT id,name FROM users WHERE org=? AND role IN ('learner','graduate') AND active=1",u.org);
  const details=[];for(const person of people){const p=await rows(c,'SELECT unit,best_score,passed,attempts FROM study_progress WHERE user_id=? AND content_version=?',person.id,studyVersion);const works=await rows(c,'SELECT unit FROM study_work WHERE user_id=? AND content_version=?',person.id,studyVersion);details.push({...person,subjects:subjects.map(s=>{const ids=new Set(studyUnits.filter(u=>u.subject===s.id).map(u=>u.id));return {subject:s.id,started:p.filter((x:any)=>ids.has(x.unit)).length,passed:p.filter((x:any)=>ids.has(x.unit)&&x.passed).length,works:works.filter((x:any)=>ids.has(x.unit)).length}}),started:p.length,passed:p.filter((x:any)=>x.passed).length,works:works.length,needsPractice:p.filter((x:any)=>!x.passed).map((x:any)=>x.unit)});}
  return json({units:studyUnits.length,people:u.role==='lcr'?[]:details,summary:{subjects:subjects.map(s=>({subject:s.id,started:details.reduce((n,x)=>n+(x.subjects.find(t=>t.subject===s.id)?.started||0),0),passed:details.reduce((n,x)=>n+(x.subjects.find(t=>t.subject===s.id)?.passed||0),0),works:details.reduce((n,x)=>n+(x.subjects.find(t=>t.subject===s.id)?.works||0),0)})),learners:people.length,started:details.reduce((n,x)=>n+x.started,0),passed:details.reduce((n,x)=>n+x.passed,0),works:details.reduce((n,x)=>n+x.works,0)}});
 }
 if(['study-check','study-work'].includes(p[0])&&method==='POST'){
  need(u,['learner']);const b:any=await readBody(r);const unit=studyUnits.find(x=>x.id===b.unit);if(!unit)fail(404,'Lekce nebyla nalezena.');if(b.contentVersion!==studyVersion)fail(409,'Obsah lekce se změnil. Otevřete aktuální verzi.');
  return json(await mutate(c,u,b,async()=>{
   const id=u!.id+':'+unit.id+':'+studyVersion;const updated=now();
   if(p[0]==='study-check'){
    if(!b.answers||typeof b.answers!=='object'||Object.keys(b.answers).length!==unit.quiz.length||unit.quiz.some((q:any)=>!q.options.some((o:any)=>o.id===b.answers[q.id])))fail(400,'Vyberte jednu platnou odpověď u každé otázky.');
    const current=await one(c,'SELECT * FROM study_progress WHERE id=?',id);if((current?.version??0)!==b.version)fail(409,'Výsledek se změnil v jiném okně. Obnovte lekci.');
    const feedback=unit.quiz.map((q:any)=>({id:q.id,correct:b.answers[q.id]===q.correct,answer:q.correct,explanation:q.explanation}));const score=feedback.filter((x:any)=>x.correct).length;const passed=score===unit.quiz.length?1:(current?.passed??0);const best=Math.max(score,current?.best_score??0);const version=(current?.version??0)+1;const attempts=(current?.attempts??0)+1;
    if(current)await run(c,'UPDATE study_progress SET answers=?,attempts=?,best_score=?,last_score=?,passed=?,version=?,updated=? WHERE id=? AND version=?',JSON.stringify(b.answers),attempts,best,score,passed,version,updated,id,b.version);
    else await run(c,'INSERT INTO study_progress (id,user_id,unit,content_version,answers,attempts,best_score,last_score,passed,version,updated) VALUES (?,?,?,?,?,?,?,?,?,?,?)',id,u!.id,unit.id,studyVersion,JSON.stringify(b.answers),attempts,best,score,passed,version,updated);
    await run(c,'INSERT INTO study_attempts (id,user_id,unit,content_version,answers,score,total,created) VALUES (?,?,?,?,?,?,?,?)',u!.id+':'+b.eventId,u!.id,unit.id,studyVersion,JSON.stringify(b.answers),score,unit.quiz.length,updated);
    if(score===unit.quiz.length)await run(c,'INSERT OR IGNORE INTO rewards VALUES (?,?,?,?,?)','study-quiz:'+id,u!.id,10,'Tři vysvětlená rozhodnutí · '+unit.title,updated);
    await log(c,u!,'study_quiz_completed',unit.id);return {ok:true,score,total:unit.quiz.length,feedback,version,passed:!!passed,best,attempts};
   }
   if(typeof b.text!=='string'||b.text.trim().length<30||b.text.length>12000)fail(400,'Napište vlastní pracovní zápis (30 až 12 000 znaků).');
   const current=await one(c,'SELECT * FROM study_work WHERE id=?',id);if((current?.version??0)!==b.version)fail(409,'Zápis má novější verzi. Obnovte lekci, ať jej nepřepíšete.');const version=(current?.version??0)+1;
   if(current)await run(c,'UPDATE study_work SET text=?,version=?,updated=? WHERE id=? AND version=?',b.text.trim(),version,updated,id,b.version);
   else await run(c,'INSERT INTO study_work (id,user_id,unit,content_version,title,text,version,created,updated) VALUES (?,?,?,?,?,?,?,?,?)',id,u!.id,unit.id,studyVersion,unit.task.title,b.text.trim(),version,updated,updated);
   await run(c,'INSERT OR IGNORE INTO rewards VALUES (?,?,?,?,?)','study-work:'+id,u!.id,5,'Vlastní pracovní zápis · '+unit.title,updated);
   await log(c,u!,'study_work_saved',unit.id);return {ok:true,id,version,updated};
  }));
 }
 if(p[0]==='logout'){if(method!=='POST')fail(405,'Použijte odhlášení.');const t=sessionToken(c,r)||'';await run(c,'DELETE FROM sessions WHERE token=?',await hash(t));return json({ok:true},200,{'Set-Cookie':'academy_session=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0'});}
 if(p[0]==='bootstrap'&&method==='GET'){
  await ensureForestry(c);
  const content=await Promise.all(missions.map(m=>missionContent(c,m.id)));let people:any[]=[];if(u.role==='instructor')people=await rows(c,'SELECT u.* FROM users u JOIN assignments a ON a.learner=u.id WHERE a.instructor=? AND u.org=? AND u.active=1',u.id,u.org);else if(['coordinator','ivp_quality','admin'].includes(u.role))people=await rows(c,"SELECT * FROM users WHERE org=? AND role IN ('learner','graduate') AND active=1",u.org);
  const work=learnerRoles.includes(u.role)?await attemptsFor(c,u.id):[];const rewards=learnerRoles.includes(u.role)?await rows(c,'SELECT * FROM rewards WHERE user_id=?',u.id):[];
  return json({user:publicUser(u),missions:content.map(m=>u!.role==='graduate'?{id:m.id,title:m.title,module_id:m.module_id,competency_ids:m.competency_ids}:safeMission(m)),competencies:competencySource.competencies,modules:moduleSource.modules,people:people.map(publicUser),attempts:work,points:rewards.reduce((s:number,x:any)=>s+x.points,0),demo:true,launcherAllowed:c.launcherAllowed});
 }
 if(p[0]==='learner'&&method==='GET'){const id=p[1];await own(c,u,id,true);const attempts=await attemptsFor(c,id);return json({user:publicUser(await one(c,'SELECT * FROM users WHERE id=?',id)),attempts,reflections:(await rows(c,'SELECT * FROM reflections WHERE user_id=?'+(u.id===id?'':' AND shared=1'),id)),practice:(await rows(c,'SELECT * FROM practice WHERE user_id=?',id)).map((x:any)=>({...x,data:parse(x.data)}))});}
 if(p[0]==='mission'&&method==='GET'){if(missions.some(m=>m.id===p[1]&&m.forestry))await ensureForestry(c);const m=await pinnedMission(c,u.id,p[1]);need(u,['learner','instructor','teacher','content_expert','didactic_reviewer']);const draft=u.role==='learner'?await one(c,'SELECT * FROM drafts WHERE id=?',u.id+':'+p[1]):null;const a=u.role==='learner'?(await attemptsFor(c,u.id)).filter((x:any)=>x.mission===p[1]):[];const reflection=await one(c,'SELECT * FROM reflections WHERE id=?',u.id+':'+p[1]);return json({mission:u.role==='learner'?safeMission(m):m,draft:draft?{...draft,data:parse(draft.data)}:null,attempts:a,reflection,attachments:u.role==='learner'?await rows(c,'SELECT id,name,mime,size FROM attachments WHERE user_id=? AND mission=?',u.id,p[1]):[]});}
 if(p[0]==='check'&&method==='POST'){need(u,['learner']);const b:any=await readBody(r);if(!str(b.contentId))fail(400,'Chybí verze zobrazeného zadání.');const m=await pinnedMission(c,u.id,b.mission,b.contentId);if(b.checkId){const q=m.forestry?.checks.find((q:any)=>q.id===b.checkId);if(!q)fail(400,'Cvičení v této verzi neexistuje.');return json({correct:b.choice===q.correct,feedback:q.feedback});}const trainingResults=m.forestry?.checks.map((q:any)=>({id:q.id,choice:b.training?.[q.id]||'',correct:b.training?.[q.id]===q.correct}));const trainingCorrect=!trainingResults||trainingResults.every((q:any)=>q.correct);return json({correct:b.choice===m.correct_option_id,trainingCorrect,trainingResults,feedback:m.feedback+(!trainingCorrect?' Vrať se také k nevyřešeným cvičením výše.':''),next:b.choice===m.correct_option_id&&trainingCorrect?'Zpracujte vlastní odpověď a jinou situaci.':'Vraťte se k přípravě a zkuste rozhodnutí znovu.'});}
 if(p[0]==='draft'&&method==='POST'){need(u,['learner']);const b:any=await readBody(r);return json(await mutate(c,u,b,async()=>{if(b.expectedUserId!==u!.id)fail(409,'Účet rozpracované odpovědi neodpovídá přihlášení.');if(!str(b.contentId))fail(400,'Chybí verze zobrazeného zadání.');const m=await pinnedMission(c,u!.id,b.mission,b.contentId);const id=u!.id+':'+m.id;const old=await one(c,'SELECT * FROM drafts WHERE id=?',id);const version=old?.version??0;if(b.version!==version)fail(409,'Na serveru je novější verze. Načtěte ji a porovnejte své změny.');if(typeof b.answer==='string'&&b.answer.length>12000||typeof b.transfer==='string'&&b.transfer.length>12000)fail(400,'Odpověď má nejvýše 12 000 znaků. Zkrať text; původní uložená verze se nemění.');const training=m.forestry?Object.fromEntries(m.forestry.checks.filter((q:any)=>q.options.some((o:any)=>o.id===b.training?.[q.id])).map((q:any)=>[q.id,b.training[q.id]])):undefined;const data={choice:str(b.choice,1),answer:str(b.answer),transfer:str(b.transfer),...(training?{training}:{})};const stamp=now();if(old){const res=await run(c,'UPDATE drafts SET data=?,version=version+1,updated=? WHERE id=? AND version=?',JSON.stringify(data),stamp,id,version);if(res.meta?.changes===0)fail(409,'Verze se změnila během ukládání.');}else{await run(c,'INSERT INTO drafts VALUES (?,?,?,?,?,?,?)',id,u!.id,m.id,1,m.contentId,JSON.stringify(data),stamp);}await log(c,u!,'draft_saved',id);return {ok:true,version:version+1,updated:stamp};}));}
 if(p[0]==='submit'&&method==='POST'){need(u,['learner']);const b:any=await readBody(r);return json(await mutate(c,u,b,async()=>{const m=await pinnedMission(c,u!.id,b.mission);const id=u!.id+':'+b.eventId;const existing=await one(c,'SELECT id FROM attempts WHERE id=?',id);if(existing)return {ok:true,id:existing.id};const draft=await one(c,'SELECT * FROM drafts WHERE id=?',u!.id+':'+m.id);if(!draft||draft.version!==b.version)fail(409,'Nejprve uložte aktuální odpověď.');const data=parse(draft.data);if(!m.options.some((o:any)=>o.id===data.choice)||str(data.answer).length<10||str(data.transfer).length<5)fail(400,'Vyberte odpověď a doplňte vlastní výstup i přenos do další situace.');if(m.forestry&&(data.choice!==m.correct_option_id||m.forestry.checks.some((q:any)=>data.training?.[q.id]!==q.correct)))fail(400,'Nejdříve vyřešte všechna cvičení a ověřte závěrečné rozhodnutí.');const history=(await attemptsFor(c,u!.id)).filter((a:any)=>a.mission===m.id);if(history[0]&&history[0].status!=='returned')fail(409,'Pokus již čeká na hodnocení nebo je uznaný.');const content=await one(c,'SELECT data FROM contents WHERE id=?',draft.content_id);const revision=history.length+1;await c.DB.batch([SQL(c,'INSERT INTO attempts VALUES (?,?,?,?,?,?,?,?)',id,u!.id,m.id,revision,draft.content_id,content.data,JSON.stringify(data),now()),SQL(c,'INSERT OR IGNORE INTO rewards VALUES (?,?,?,?,?)',u!.id+':lesson:'+draft.content_id,u!.id,10,'Vlastní vysvětlení k modelové lekci',now())]);await log(c,u!,'attempt_submitted',id);return {ok:true,id,revision};}));}
 if(p[0]==='review'&&method==='POST'){need(u,['instructor']);const b:any=await readBody(r);return json(await mutate(c,u,b,async()=>{const a=await one(c,'SELECT * FROM attempts WHERE id=?',b.attemptId);if(!a)fail(404,'Pokus nebyl nalezen.');await own(c,u!,a.user_id,true);const old=await one(c,'SELECT * FROM assessments WHERE attempt_id=? ORDER BY revision DESC LIMIT 1',a.id);if((old?.revision??0)!==b.version)fail(409,'Hodnocení se mezitím změnilo.');if(old&&!str(b.reason))fail(400,'Změna hodnocení vyžaduje důvod nové revize.');const newer=await one(c,'SELECT id FROM attempts WHERE user_id=? AND mission=? AND revision>?',a.user_id,a.mission,a.revision);if(newer)fail(409,'Účastník už odevzdal novější pokus.');const data=validateAssessment(b);const id=u!.id+':'+b.eventId;const statements=[SQL(c,'INSERT INTO assessments VALUES (?,?,?,?,?,?)',id,a.id,u!.id,(old?.revision??0)+1,JSON.stringify(data),now())];if(data.outcome==='accepted'&&a.revision>1)statements.push(SQL(c,'INSERT OR IGNORE INTO rewards VALUES (?,?,?,?,?)','correction:'+a.id,a.user_id,10,'Doložená oprava uznaná instruktorem',now()));await c.DB.batch(statements);await log(c,u!,'assessment_revision',id);return {ok:true,id};}));}
 if(p[0]==='review-evidence'&&method==='GET'){need(u,['instructor']);const a=await one(c,'SELECT * FROM attempts WHERE id=?',p[1]);if(!a)fail(404,'Odevzdání nebylo nalezeno.');await own(c,u,a.user_id,true);const attachments=await rows(c,'SELECT id,name,mime,size,created FROM attachments WHERE user_id=? AND mission=? AND created<=?',a.user_id,a.mission,a.created);const reflection=await one(c,'SELECT text,version FROM reflections WHERE user_id=? AND mission=? AND shared=1',a.user_id,a.mission);return json({attemptId:a.id,attachments,reflection:reflection||null});}
 if(p[0]==='queue'&&method==='GET'){need(u,['instructor']);const assigned=await rows(c,'SELECT a.learner FROM assignments a JOIN users u ON u.id=a.learner WHERE a.instructor=? AND u.active=1 AND u.org=?',u.id,u.org);let result:any[]=[];for(const a of assigned){await own(c,u,a.learner,true);const all=await attemptsFor(c,a.learner,true);result.push(...all.filter((x:any)=>!all.some((y:any)=>y.mission===x.mission&&y.revision>x.revision)));}return json({items:result});}
 if(p[0]==='reflection'){const id=url.searchParams.get('user')||u.id;await own(c,u,id,true);if(method==='GET'){const d=await one(c,'SELECT * FROM reflections WHERE id=?',id+':'+p[1]);if(d&&id!==u.id&&!d.shared)fail(403,'Tato reflexe je soukromá.');return json(d);}need(u,['learner']);const b:any=await readBody(r);const old=await one(c,'SELECT * FROM reflections WHERE id=?',u.id+':'+b.mission);if((old?.version??0)!==b.version)fail(409,'Reflexe má novější verzi.');if(old){const r=await run(c,'UPDATE reflections SET text=?,shared=?,version=version+1 WHERE id=? AND version=?',str(b.text),b.shared?1:0,u.id+':'+b.mission,b.version);if(!r.meta?.changes)fail(409,'Reflexe se mezitím změnila.');}else{try{await run(c,'INSERT INTO reflections VALUES (?,?,?,?,?,1)',u.id+':'+b.mission,u.id,b.mission,str(b.text),b.shared?1:0)}catch{fail(409,'Reflexe se mezitím změnila.');}}await log(c,u,'reflection_updated',b.mission);return json({ok:true,version:(old?.version??0)+1});}
 if(p[0]==='portfolio-entry'&&method==='POST'){need(u,['learner']);const b=await readBody(r);if(b.kind!=='seen')fail(400,'Vlastní záznam může doložit pouze návštěvu ukázky, ne ověřený výkon.');const competencyIds=[...new Set(Array.isArray(b.competencyIds)?b.competencyIds:[])];if(competencyIds.some(id=>!competencySource.competencies.some(x=>x.id===id)))fail(400,'Neznámá oblast profilu.');const evidenceIds=[...new Set(Array.isArray(b.evidenceIds)?b.evidenceIds:[])];for(const id of evidenceIds){const f=await one(c,'SELECT user_id FROM attachments WHERE id=?',id);if(!f||f.user_id!==u.id)fail(403,'Příloha není vaše.');}const evidenceMappings=evidenceIds.flatMap(attachmentId=>competencyIds.map(competencyId=>({attachmentId,competencyId,scope:'Doklad návštěvy, nikoli samostatné pozorování výkonu'})));const data={evidenceMappings,kind:'seen',status:'seen',title:str(b.title,180),details:str(b.details),occurredAt:str(b.occurredAt,40)||null,competencyIds,evidenceIds,source:'Vlastní záznam účastníka · DEMO',practicalVerified:false};if(!data.title||!data.details)fail(400,'Doplňte název ukázky a konkrétní poznámku.');const id=uid();await run(c,'INSERT INTO portfolio_entries VALUES (?,?,?,?)',id,u.id,JSON.stringify(data),now());await log(c,u,'portfolio_seen_added',id);return json({ok:true,id});}
 if(p[0]==='portfolio'&&method==='GET')return json(await portfolio(c,u,url.searchParams.get('user')||u.id));
 if(p[0]==='export'&&method==='POST'){need(u,learnerRoles);const b:any=await readBody(r);if(b.user&&b.user!==u.id)fail(403,'Cizí portfolio nelze exportovat.');const all=await portfolio(c,u,u.id);if(!Array.isArray(b.ids)||b.ids.some((id:string)=>!all.items.some((a:any)=>a.id===id)))fail(403,'Výběr obsahuje nepovolenou položku.');const selected=all.items.filter((a:any)=>b.ids.includes(a.id));return json({title:'Portfolio DEMO — není osvědčením odborné způsobilosti',owner:u.name,exportedAt:now(),items:selected,demo:true},200,{'Content-Disposition':'attachment; filename="Portfolio_DEMO.json"'});}
 if(p[0]==='shares'){need(u,learnerRoles);if(method==='GET')return json(await rows(c,'SELECT id,items,expires,revoked FROM shares WHERE user_id=?',u.id));const b:any=await readBody(r);if(b.action==='revoke'){await run(c,'UPDATE shares SET revoked=1 WHERE id=? AND user_id=?',b.id,u.id);await log(c,u,'share_revoked',b.id);return json({ok:true});}const all=await portfolio(c,u,u.id);if(!Array.isArray(b.ids)||!b.ids.length||b.ids.some((id:string)=>!all.items.some((a:any)=>a.id===id)))fail(403,'Vyberte pouze vlastní položky.');const token=rawToken();const id=uid();const expires=Date.now()+Math.min(168,Math.max(1,Number(b.hours)||24))*3600000;await run(c,'INSERT INTO shares VALUES (?,?,?,?,?,0)',id,await hash(token),u.id,JSON.stringify(b.ids),expires);await log(c,u,'share_created',id);return json({id,token,expires,path:'/overeni/'+token});}
 if(p[0]==='attachment'){
  if(method==='GET'){const f=await one(c,'SELECT * FROM attachments WHERE id=?',p[1]);if(!f)fail(404,'Příloha nebyla nalezena.');await own(c,u,f.user_id,true);const obj=await c.BUCKET.get(f.r2key);if(!obj)fail(404,'Soubor není dostupný.');return new Response(obj.body,{headers:{'Content-Type':f.mime,'Content-Disposition':`attachment; filename="${f.name.replace(/[^a-zA-Z0-9_.-]/g,'_')}"`,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; sandbox"}});}
  need(u,['learner']);const form=await r.formData();if(form.get('expectedUserId')!==u.id)fail(409,'Účet se změnil. Příloha nebyla uložena.');const file=form.get('file') as File;const mission=str(form.get('mission'),10);await missionContent(c,mission);if(!file||typeof file.arrayBuffer!=='function')fail(400,'Vyberte soubor.');if(file.size>5_000_000||file.size===0)fail(400,'Příloha má být neprázdná a nejvýše 5 MB.');if(!['image/png','image/jpeg','text/plain'].includes(file.type))fail(400,'Povolené přílohy: PNG, JPEG nebo TXT.');const bytes=new Uint8Array(await file.arrayBuffer());if(file.type==='image/png'&&![137,80,78,71,13,10,26,10].every((v,i)=>bytes[i]===v))fail(400,'Obsah neodpovídá PNG.');if(file.type==='image/jpeg'&&(bytes[0]!==255||bytes[1]!==216||bytes[2]!==255))fail(400,'Obsah neodpovídá JPEG.');if(file.type==='text/plain'&&(bytes.includes(0)||/<(?:script|html|svg)/i.test(new TextDecoder().decode(bytes))))fail(400,'Aktivní obsah není povolen.');const digest=await crypto.subtle.digest('SHA-256',bytes);const id=await hash(u.id+':'+mission+':'+file.name+':'+Array.from(new Uint8Array(digest)).join(','));const exists=await one(c,'SELECT id FROM attachments WHERE id=?',id);if(exists)return json({ok:true,id});const key=u.org+'/'+u.id+'/'+id;await c.BUCKET.put(key,bytes,{httpMetadata:{contentType:file.type}});try{await run(c,'INSERT INTO attachments VALUES (?,?,?,?,?,?,?,?)',id,u.id,mission,str(file.name,120),file.type,file.size,key,now());}catch(e){if(await one(c,'SELECT id FROM attachments WHERE id=?',id))return json({ok:true,id});await c.BUCKET.delete(key);throw e}await log(c,u,'attachment_added',id);return json({ok:true,id});
 }
 if(p[0]==='practice'){
  if(method==='GET'){let list:any[]=[];if(learnerRoles.includes(u.role))list=await rows(c,'SELECT * FROM practice WHERE user_id=?',u.id);else if(u.role==='instructor')list=await rows(c,'SELECT p.* FROM practice p JOIN assignments a ON a.learner=p.user_id WHERE a.instructor=?',u.id);else{need(u,['coordinator','ivp_quality']);list=await rows(c,'SELECT p.* FROM practice p JOIN users u ON u.id=p.user_id WHERE u.org=?',u.org);}for(const x of list){x.data=parse(x.data);x.observations=(await rows(c,'SELECT * FROM observations WHERE practice_id=? ORDER BY revision DESC',x.id)).map((o:any)=>({...o,data:parse(o.data)}));x.eligible=eligible(x.data);}return json({items:list});}
  const b:any=await readBody(r);need(u,['coordinator']);const target=await one(c,"SELECT * FROM users WHERE id=? AND org=? AND role='learner' AND active=1",b.userId,u.org);if(!target)fail(403,'Účastník není v tomto běhu.');const data={title:str(b.title,180),place:str(b.place,180)||'DEMO-Sever · učebna',date:str(b.date,40)||null,hours:b.hours===null||b.hours===undefined||b.hours===''?null:Math.max(0,Math.min(1000,Number(b.hours)||0)),season:null,scope:'Pouze modelová situace bez skutečné práce',requirementStatus:'unknown',requirementScope:null,expires:null,productionEnabled:false};if(b.missionId){const m=await missionContent(c,str(b.missionId,10));if(!m.forestry)fail(400,'Vyberte odbornou lekci.');Object.assign(data,{missionId:m.id,contentId:m.contentId,title:m.title+' · praktický nácvik',competencyIds:m.competency_ids,practiceBrief:m.forestry.practice,criteria:m.forestry.criteria,sourceStatus:m.forestry.approval,scope:'Plán nácviku podle lekce. V DEMO se ověřuje jen modelový výkon; skutečné pracoviště a podmínky schválí LČR / ČZU.'});}if(!data.title)fail(400,'Doplňte název příležitosti.');const id=uid();await run(c,'INSERT INTO practice VALUES (?,?,?,1)',id,b.userId,JSON.stringify(data));await log(c,u,'practice_planned',id);return json({ok:true,id});
 }
 if(p[0]==='requirement'&&method==='POST'){need(u,['instructor']);const b:any=await readBody(r);const p=await one(c,'SELECT * FROM practice WHERE id=?',b.id);if(!p)fail(404,'Aktivita nebyla nalezena.');await own(c,u,p.user_id,true);if(p.version!==b.version)fail(409,'Aktivita má novější verzi.');if(!str(b.scope)||!str(b.reason))fail(400,'Vyplňte rozsah a podklad ověření.');if(b.expires!==null&&b.expires!==undefined&&b.expires!==''&&(!Number.isFinite(Date.parse(b.expires))||!/^\d{4}-\d{2}-\d{2}T/.test(b.expires)))fail(400,'Platnost musí být platný datum a čas.');const d=parse(p.data);d.requirementStatus=b.verified?'verified_demo':'not_met';d.requirementScope=str(b.scope);d.verifiedBy=u.id;d.verifiedAt=now();d.expires=b.expires||null;d.verificationReason=str(b.reason);const out=await run(c,'UPDATE practice SET data=?,version=version+1 WHERE id=? AND version=?',JSON.stringify(d),p.id,p.version);if(!out.meta?.changes)fail(409,'Současná změna aktivity.');await log(c,u,'requirement_verified_demo',JSON.stringify({id:p.id,version:p.version+1,before:parse(p.data),after:d}));return json({ok:true});}
 if(p[0]==='observe'&&method==='POST'){need(u,['instructor']);const b:any=await readBody(r);return json(await mutate(c,u,b,async()=>{const p=await one(c,'SELECT * FROM practice WHERE id=?',b.practiceId);if(!p)fail(404,'Aktivita nebyla nalezena.');await own(c,u!,p.user_id,true);const data=validateAssessment(b);const d=parse(p.data);if(data.outcome==='accepted'&&!eligible(d))fail(409,'Předpoklad není ověřený nebo jeho platnost skončila.');const previous=await one(c,'SELECT * FROM observations WHERE practice_id=? ORDER BY revision DESC LIMIT 1',p.id);if((previous?.revision??0)!==b.version)fail(409,'Pozorování má novější revizi.');if(previous&&!str(b.reason))fail(400,'Nová revize vyžaduje důvod.');const id=u!.id+':'+b.eventId;if(b.practiceVersion!==undefined&&b.practiceVersion!==p.version)fail(409,'Předpoklady aktivity se mezitím změnily.');await run(c,'INSERT INTO observations SELECT ?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM practice WHERE id=? AND version=?)',id,p.id,u!.id,(previous?.revision??0)+1,JSON.stringify({...data,occurredAt:b.occurredAt||now(),conditions:str(b.conditions),place:d.place,activitySnapshot:d}),now(),p.id,p.version);await log(c,u!,'observation_revision',id);return {ok:true,id};}));}
 if(p[0]==='mentoring'){
  if(method==='GET'){let data;if(learnerRoles.includes(u.role))data=await rows(c,'SELECT * FROM mentors WHERE user_id=? ORDER BY created DESC',u.id);else{need(u,['instructor']);data=await rows(c,'SELECT m.* FROM mentors m JOIN assignments a ON a.learner=m.user_id WHERE a.instructor=? ORDER BY m.created DESC',u.id);}return json(data.map((x:any)=>({...x,data:parse(x.data)})));}
  need(u,['learner','instructor']);const b:any=await readBody(r);const learner=u.role==='learner'?u.id:b.userId;await own(c,u,learner,true);const a=await one(c,'SELECT instructor FROM assignments WHERE learner=?',learner);if(!a)fail(409,'Mentor zatím není přidělen.');const data={topic:str(b.topic,300),next:str(b.next,2000),responsible:str(b.responsible,180),date:str(b.date,40),status:u.role==='instructor'?'agreed':'requested',scope:'Sdíleno s účastníkem a přiděleným mentorem'};if(!data.topic||!data.next||!data.responsible||!data.date)fail(400,'Vyplňte téma, další krok, odpovědnou osobu a termín.');const id=uid();await run(c,'INSERT INTO mentors VALUES (?,?,?,?,?)',id,learner,a.instructor,JSON.stringify(data),now());await log(c,u,'mentoring_'+data.status,id);return json({ok:true,id});
 }
 if(p[0]==='content'){
  need(u,['teacher','content_expert','didactic_reviewer','ivp_quality']);if(method==='GET'){const data=await rows(c,'SELECT * FROM contents ORDER BY mission,revision DESC');for(const d of data){d.data=parse(d.data);d.approvals=await rows(c,'SELECT * FROM approvals WHERE content_id=?',d.id);}return json({items:data});}
  const b:any=await readBody(r);if(b.productionEnabled||b.action==='publish_production')fail(409,'Ostré schválení je blokováno otevřenými požadavky LČR a ČZU.');
  if(b.action==='create'){need(u,['teacher']);const base=await missionContent(c,b.mission);const latest=await one(c,'SELECT MAX(revision) AS n FROM contents WHERE mission=?',b.mission);const data={...base,...(base.forestry?forestryProposal(b,base):{}),title:str(b.title,180),lesson_text:str(b.lesson),scenario:str(b.scenario),submission_task:str(b.task),transfer_task:str(b.transfer),proposed_assessor_guidance:str(b.criteria),production_enabled:false};if(!data.title||!data.lesson_text||!data.scenario||!data.submission_task||!data.transfer_task||!data.proposed_assessor_guidance)fail(400,'Vyplňte název, přípravu, scénář, výstup a kritéria.');const id=uid();await run(c,'INSERT INTO contents VALUES (?,?,?,?,?,?,?)',id,b.mission,latest.n+1,u.id,'expert_review',JSON.stringify(data),now());await log(c,u,'content_version_created',id);return json({ok:true,id});}
  const content=await one(c,'SELECT * FROM contents WHERE id=?',b.id);if(!content)fail(404,'Verze nebyla nalezena.');if(b.action==='approve'){
   need(u,['content_expert','didactic_reviewer']);if(content.author===u.id)fail(403,'Autor nemůže recenzovat vlastní verzi.');const expected=u.role==='content_expert'?'expert_review':'didactic_review';if(content.status!==expected)fail(409,'Tato verze nečeká na vaši recenzi.');if(!str(b.note))fail(400,'Doplňte rozsah a závěr recenze.');await c.DB.batch([SQL(c,'INSERT INTO approvals VALUES (?,?,?,?,?,?)',uid(),content.id,u.id,u.role,str(b.note),now()),SQL(c,'UPDATE contents SET status=? WHERE id=? AND status=?',u.role==='content_expert'?'didactic_review':'approved_demo',content.id,expected)]);await log(c,u,'content_approved_demo',content.id);return json({ok:true});}
  if(b.action==='publish'){need(u,['teacher']);const a=await rows(c,'SELECT role FROM approvals WHERE content_id=?',content.id);if(content.status!=='approved_demo'||!['content_expert','didactic_reviewer'].every(r=>a.some((x:any)=>x.role===r)))fail(409,'Tato přesná verze nemá obě recenze.');await c.DB.batch([SQL(c,"UPDATE contents SET status='superseded' WHERE mission=? AND status='published_demo'",content.mission),SQL(c,"UPDATE contents SET status='published_demo' WHERE id=?",content.id)]);await log(c,u,'content_published_demo',content.id);return json({ok:true});}
  fail(400,'Neznámá akce obsahu.');
 }
 if(p[0]==='ivp'&&method==='GET'){need(u,['ivp_quality','coordinator','lcr']);const people=await rows(c,"SELECT u.id,u.name,u.role,a.instructor FROM users u LEFT JOIN assignments a ON a.learner=u.id WHERE u.org=? AND u.role IN ('learner','graduate') AND u.active=1",u.org);const details=[];for(const p of people){const a=await attemptsFor(c,p.id);const pending=a.filter((x:any)=>x.status==='submitted').length;const pr=await rows(c,'SELECT * FROM practice WHERE user_id=?',p.id);const obs=await rows(c,'SELECT o.* FROM observations o JOIN practice p ON p.id=o.practice_id WHERE p.user_id=? AND o.revision=(SELECT MAX(o2.revision) FROM observations o2 WHERE o2.practice_id=o.practice_id)',p.id);const latest=a.filter((x:any)=>!a.some((y:any)=>y.mission===x.mission&&y.revision>x.revision));details.push({...p,missingEvidence:pr.filter((x:any)=>!obs.some((o:any)=>o.practice_id===x.id)).length,records:[...latest.map((x:any)=>({id:x.id,label:x.mission+' · pokus '+x.revision,status:x.status,kind:'Modelová mise'})),...pr.map((x:any)=>({id:x.id,label:parse(x.data).title,status:obs.some((o:any)=>o.practice_id===x.id)?'Pozorování zapsáno':'Chybí pozorování',kind:'Příležitost k praxi'})),...obs.map((x:any)=>({id:x.id,label:'Pozorování · revize '+x.revision,status:parse(x.data).outcome,kind:'Pozorování · aktivita '+x.practice_id}))],submitted:a.length,pending,accepted:a.filter((x:any)=>x.status==='accepted').length,opportunities:pr.length,missingPrerequisites:pr.filter((x:any)=>{const d=parse(x.data);return !eligible(d)}).length,critical:obs.filter((x:any)=>parse(x.data).critical).length});}const summary={learners:people.length,pending:details.reduce((s,x)=>s+x.pending,0),noOpportunity:details.filter(x=>x.opportunities===0).length,critical:details.reduce((s,x)=>s+x.critical,0),practicalVerified:0,award:'Čeká na schválení programu'};return json({summary,people:u.role==='lcr'?[]:details,schedule:parse((await one(c,"SELECT data FROM settings WHERE id='schedule'"))?.data),audit:u.role==='ivp_quality'?await rows(c,'SELECT * FROM audit WHERE org=? ORDER BY created DESC LIMIT 80',u.org):[]});}
 if(p[0]==='schedule'){need(u,['coordinator','ivp_quality']);if(method==='GET'){const d=await one(c,"SELECT * FROM settings WHERE id='schedule'");const schedule=parse(d?.data);return json({...d,data:{...schedule,blocks:schedule.blocks||moduleSource.modules.map(m=>({moduleId:m.id,title:m.name,date:null,hours:null,place:null,season:null,status:'proposal'}))}});}need(u,['coordinator']);const b:any=await readBody(r);if(!['open','six_months_proposal','twelve_months_proposal','custom_proposal'].includes(b.variant))fail(400,'Neplatná varianta.');const previousPlan=await one(c,"SELECT * FROM settings WHERE id='schedule'");const blocks=Array.isArray(b.blocks)?b.blocks:parse(previousPlan.data).blocks||moduleSource.modules.map(m=>({moduleId:m.id,title:m.name,date:null,hours:null,place:null,season:null,status:'proposal'}));if(blocks.some((x:any)=>!moduleSource.modules.some(m=>m.id===x.moduleId))||new Set(blocks.map((x:any)=>x.moduleId)).size!==blocks.length)fail(400,'Bloky musí mít jedinečné známé ID.');if(b.durationMonths!==null&&b.durationMonths!==undefined&&b.durationMonths!==''&&(!Number.isFinite(Number(b.durationMonths))||Number(b.durationMonths)<1||Number(b.durationMonths)>60))fail(400,'Navržená délka musí být 1 až 60 měsíců, nebo neznámá.');if(blocks.some((x:any)=>(x.date&&(!/^\d{4}-\d{2}-\d{2}$/.test(x.date)||!Number.isFinite(Date.parse(x.date))||new Date(x.date).toISOString().slice(0,10)!==x.date))||(x.hours!==null&&x.hours!==undefined&&x.hours!==''&&(!Number.isFinite(Number(x.hours))||Number(x.hours)<0||Number(x.hours)>1000))))fail(400,'Opravte datum nebo navržené hodiny bloku.');const proposedBlocks=blocks.map((x:any)=>({moduleId:x.moduleId,title:moduleSource.modules.find(m=>m.id===x.moduleId)!.name,date:str(x.date,40)||null,hours:x.hours===null||x.hours===undefined||x.hours===''?null:Math.max(0,Math.min(1000,Number(x.hours)||0)),place:str(x.place,180)||null,season:null,status:'proposal'}));const data={blocks:proposedBlocks,variant:b.variant,durationMonths:b.durationMonths?Number(b.durationMonths):null,grouping:b.grouping==='15+15'?'15+15':'open',notes:str(b.notes),status:'proposal',seasonWindows:null};const updated=await run(c,"UPDATE settings SET data=?,version=version+1 WHERE id='schedule' AND version=?",JSON.stringify(data),b.version);if(!updated.meta?.changes)fail(409,'Plán má novější verzi.');await log(c,u,'schedule_updated',JSON.stringify({id:'schedule',version:b.version+1,before:parse(previousPlan.data),after:data}));return json({ok:true});}
 if(p[0]==='account'&&method==='POST'){need(u,['coordinator','admin']);const b:any=await readBody(r);const target=await one(c,"SELECT * FROM users WHERE id=? AND org=? AND role IN ('learner','graduate')",b.id,u.org);if(!target)fail(403,'Účet není v tomto běhu.');if(!str(b.reason))fail(400,'Uveďte důvod změny.');if(b.action==='graduate'){await c.DB.batch([SQL(c,"UPDATE users SET role='graduate' WHERE id=?",b.id),SQL(c,'DELETE FROM sessions WHERE user_id=?',b.id),SQL(c,'UPDATE shares SET revoked=1 WHERE user_id=?',b.id)]);}else if(b.action==='deactivate'){await c.DB.batch([SQL(c,'UPDATE users SET active=0 WHERE id=?',b.id),SQL(c,'DELETE FROM sessions WHERE user_id=?',b.id),SQL(c,'UPDATE shares SET revoked=1 WHERE user_id=?',b.id)]);}else fail(400,'Neznámá akce účtu.');await log(c,u,'account_'+b.action,JSON.stringify({id:b.id,reason:str(b.reason)}));return json({ok:true});}
 if(p[0]==='assistant'&&method==='POST'){return json({mode:'source_library',aiEnabled:false,answer:'AI není v této demonstraci připojena. V dostupných schválených podkladech nelze potvrdit další odborný postup. Použijte modelovou přípravu nebo předejte otázku instruktorovi.',sources:[],next:'/podpora'});}
 if(p[0]==='award'){fail(409,'Pravidla programu nejsou schválena. DEMO nevydává osvědčení odborné způsobilosti ani mikrocertifikát.');}
 return fail(404,'Požadovaná funkce nebyla nalezena.');
 }catch(e:any){if(e instanceof Fault){if(u&&e.status===403)await log(c,u,'access_denied',new URL(r.url).pathname).catch(()=>{});return json({error:e.message},e.status);}console.error('academy_error',e?.name,e?.message);return json({error:'Uložení nebo načtení se nezdařilo. Vaše rozepsané údaje zůstávají ve formuláři. Zkuste akci znovu.'},503);}}
